In [19]:
import pandas as pd

# Cargar el archivo CSV
file_path = r'C:\Users\solan\MoodTune\data\procesando\df_80-200_p3_last_final.csv'
df = pd.read_csv(file_path)

# Mostrar las primeras filas del DataFrame
print(df.head())

# Información general del DataFrame
print(df.info())

# Descripción estadística de las columnas numéricas
print(df.describe())

         song_name               artist_name  \
0     Motherfucker                   Dwarves
1         Holy War                Brainstorm
2     Sad But True  Sixpence None the Richer
3      Blue Monday              Lisa Germano
4  Keep Me In Mind                 Cosmicity

                           recording_id  danceable  not_danceable   male  \
0  2c3486cc-e933-4f05-8dad-442eb3b47d30      0.037          0.963  0.338
1  89bb58a7-0bf4-485d-9883-a22ebd5e200d      0.979          0.021  0.330
2  79a5bc80-9162-45bd-ba51-e6f7b17b5555      0.030          0.970  0.331
3  1fef8bdd-285a-4948-be33-d994f7d28325      0.000          1.000  0.622
4  356864f4-4640-404d-944d-235e558c7481      0.957          0.043  0.036

   female  timbre_bright  timbre_dark  tonal  atonal  instrumental  voice  \
0   0.662          0.913        0.087  0.340   0.660         1.000  0.000
1   0.670          0.004        0.996  0.072   0.928         0.998  0.002
2   0.669          0.092        0.908  0.301   0.699         0.455  0.545
3   0.378          0.004        0.996  0.000   1.000         0.000  1.000
4   0.964          1.000        0.000  0.998   0.002         0.473  0.527

   dortmund_alternative  dortmund_blues  dortmund_electronic  \
0                 0.127           0.077                0.010
1                 0.001           0.000                0.999
2                 0.185           0.120                0.453
3                 0.010           0.002                0.976
4                 0.063           0.004                0.919

   dortmund_folkcountry  dortmund_funksoulrnb  dortmund_jazz  dortmund_pop  \
0                 0.050                 0.006          0.006         0.026
1                 0.000                 0.000          0.000         0.000
2                 0.080                 0.013          0.024         0.023
3                 0.002                 0.000          0.008         0.000
4                 0.009                 0.000          0.001         0.001

   dortmund_raphiphop  dortmund_rock  electronic_ambient  electronic_dnb  \
0               0.001          0.696               0.482           0.233
1               0.000          0.000               0.100           0.015
2               0.008          0.094               0.711           0.077
3               0.000          0.002               0.439           0.041
4               0.000          0.004               0.214           0.029

   electronic_house  electronic_techno  electronic_trance  rosamerica_cla  \
0             0.060              0.020              0.205           0.007
1             0.020              0.008              0.856           0.001
2             0.062              0.013              0.137           0.030
3             0.239              0.247              0.035           0.024
4             0.139              0.023              0.595           0.002

   rosamerica_dan  rosamerica_hip  rosamerica_jaz  rosamerica_pop  \
0           0.001           0.001           0.001           0.003
1           0.002           0.003           0.000           0.010
2           0.003           0.009           0.005           0.021
3           0.057           0.222           0.089           0.084
4           0.678           0.005           0.003           0.079

   rosamerica_rhy  rosamerica_roc  rosamerica_spe  tzanetakis_blu  \
0           0.001           0.986           0.001           0.063
1           0.001           0.984           0.000           0.063
2           0.017           0.914           0.001           0.063
3           0.456           0.031           0.036           0.062
4           0.102           0.128           0.002           0.063

   tzanetakis_cla  tzanetakis_cou  tzanetakis_dis  tzanetakis_hip  \
0           0.035           0.078           0.105           0.157
1           0.035           0.104           0.078           0.157
2           0.035           0.104           0.078           0.157
3           0.034           0.103           0.051           0.154
4           0.035           0.104           0.078           0.157

   tzanetakis_jaz  tzanetakis_met  tzanetakis_pop  tzanetakis_reg  \
0           0.314           0.045           0.063           0.063
1           0.314           0.045           0.063           0.063
2           0.314           0.045           0.063           0.063
3           0.309           0.044           0.077           0.062
4           0.314           0.045           0.063           0.063

   tzanetakis_roc  ismir04_rhythm_ChaChaCha  ismir04_rhythm_Jive  \
0           0.078                     0.060                0.811
1           0.078                     0.122                0.244
2           0.078                     0.674                0.059
3           0.103                     0.002                0.002
4           0.078                     0.219                0.110

   ismir04_rhythm_Quickstep  ismir04_rhythm_Rumba-American  \
0                     0.009                          0.005
1                     0.039                          0.052
2                     0.008                          0.013
3                     0.001                          0.951
4                     0.030                          0.064

   ismir04_rhythm_Rumba-International  ismir04_rhythm_Rumba-Misc  \
0                               0.003                      0.001
1                               0.040                      0.034
2                               0.007                      0.005
3                               0.007                      0.006
4                               0.073                      0.036

   ismir04_rhythm_Samba  ismir04_rhythm_Tango  ismir04_rhythm_VienneseWaltz  \
0                 0.029                 0.011                         0.065
1                 0.059                 0.113                         0.270
2                 0.017                 0.072                         0.139
3                 0.027                 0.001                         0.001
4                 0.130                 0.175                         0.143

   ismir04_rhythm_Waltz  mood_acoustic  mood_not_acoustic  mood_aggressive  \
0                 0.006          0.003              0.997            0.997
1                 0.026          0.000              1.000            0.992
2                 0.006          0.009              0.991            0.681
3                 0.001          0.096              0.904            0.000
4                 0.020          0.041              0.959            0.008

   mood_not_aggressive  mood_electronic  mood_not_electronic  mood_happy  \
0                0.003            0.055                0.945       0.138
1                0.008            0.558                0.442       0.396
2                0.319            0.302                0.698       0.515
3                1.000            0.979                0.021       0.023
4                0.992            0.274                0.726       0.354

   mood_not_happy  mood_party  mood_not_party  mood_relaxed  mood_not_relaxed  \
0           0.862       0.522           0.478         0.026             0.974
1           0.604       0.693           0.307         0.027             0.973
2           0.485       0.580           0.420         0.072             0.928
3           0.977       0.000           1.000         0.809             0.191
4           0.646       0.566           0.434         0.040             0.960

   mood_sad  mood_not_sad  mood_mirex1  mood_mirex2  mood_mirex3  mood_mirex4  \
0     0.051         0.949        0.285        0.089        0.107        0.069
1     0.057         0.943        0.048        0.029        0.056        0.033
2     0.114         0.886        0.142        0.109        0.061        0.069
3     0.265         0.735        0.077        0.044        0.228        0.031
4     0.500         0.500        0.126        0.089        0.489        0.126

   mood_mirex5                                        spotify_url  \
0        0.450  https://open.spotify.com/track/00F9LiolJIUlkDN...
1        0.835  https://open.spotify.com/track/041wOMznTDlaQJz...
2        0.618  https://open.spotify.com/track/4fBeC8N7NrajX1C...
3        0.620                                                NaN
4        0.170  https://open.spotify.com/track/4MZm6Zv0QNZCPMQ...

                                          album_name album_release_date  \
0                                Blood, Guts & Pussy         1990-01-01
1                                             Unholy         1998-08-03
2  Sixpence None The Richer (Deluxe Anniversary E...         2024-02-02
3                                                NaN                NaN
4                                     In Perspective               1998

   duration_ms  popularity language  playlist_ids  playlists_names  \
0      83400.0        35.0       en           NaN              NaN
1     233333.0         6.0       en           NaN              NaN
2     240374.0        18.0       en           NaN              NaN
3          NaN         NaN       en           NaN              NaN
4     253600.0         1.0       en           NaN              NaN

   combined_genres                                             lyrics  \
0              NaN  Well I'm a motherfucker yes this I must admit ...
1              NaN  Stir up the nation into war They will believe ...
2              NaN  If I could have the words to change To speak i...
3              NaN  So, you're goin' cross Country You're leavin' ...
4              NaN  I have been to places That I dare not go alone...

                                              genres  \
0  punk, punk rock, seen live, Garage Punk, hardcore
1  Power metal, rock, latvian, heavy metal, seen ...
2  pop, female vocalists, rock, alternative, chri...
3  singer-songwriter, female vocalists, indie, dr...
4    synthpop, electronic, ebm, futurepop, synth pop

                                                tags
0  punk, punk rock, Garage Punk, garage, Rock and...
1             heavy metal, Power metal, German metal
2                                              heart
3                                        rock, jazzy
4                               rainbowfreezepoppers
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48731 entries, 0 to 48730
Data columns (total 86 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   song_name                           48731 non-null  object
 1   artist_name                         48731 non-null  object
 2   recording_id                        48731 non-null  object
 3   danceable                           48731 non-null  float64
 4   not_danceable                       48731 non-null  float64
 5   male                                48731 non-null  float64
 6   female                              48731 non-null  float64
 7   timbre_bright                       48731 non-null  float64
 8   timbre_dark                         48731 non-null  float64
 9   tonal                               48731 non-null  float64
 10  atonal                              48731 non-null  float64
 11  instrumental                        48731 non-null  float64
 12  voice                               48731 non-null  float64
 13  dortmund_alternative                48731 non-null  float64
 14  dortmund_blues                      48731 non-null  float64
 15  dortmund_electronic                 48731 non-null  float64
 16  dortmund_folkcountry                48731 non-null  float64
 17  dortmund_funksoulrnb                48731 non-null  float64
 18  dortmund_jazz                       48731 non-null  float64
 19  dortmund_pop                        48731 non-null  float64
 20  dortmund_raphiphop                  48731 non-null  float64
 21  dortmund_rock                       48731 non-null  float64
 22  electronic_ambient                  48731 non-null  float64
 23  electronic_dnb                      48731 non-null  float64
 24  electronic_house                    48731 non-null  float64
 25  electronic_techno                   48731 non-null  float64
 26  electronic_trance                   48731 non-null  float64
 27  rosamerica_cla                      48731 non-null  float64
 28  rosamerica_dan                      48731 non-null  float64
 29  rosamerica_hip                      48731 non-null  float64
 30  rosamerica_jaz                      48731 non-null  float64
 31  rosamerica_pop                      48731 non-null  float64
 32  rosamerica_rhy                      48731 non-null  float64
 33  rosamerica_roc                      48731 non-null  float64
 34  rosamerica_spe                      48731 non-null  float64
 35  tzanetakis_blu                      48731 non-null  float64
 36  tzanetakis_cla                      48731 non-null  float64
 37  tzanetakis_cou                      48731 non-null  float64
 38  tzanetakis_dis                      48731 non-null  float64
 39  tzanetakis_hip                      48731 non-null  float64
 40  tzanetakis_jaz                      48731 non-null  float64
 41  tzanetakis_met                      48731 non-null  float64
 42  tzanetakis_pop                      48731 non-null  float64
 43  tzanetakis_reg                      48731 non-null  float64
 44  tzanetakis_roc                      48731 non-null  float64
 45  ismir04_rhythm_ChaChaCha            48731 non-null  float64
 46  ismir04_rhythm_Jive                 48731 non-null  float64
 47  ismir04_rhythm_Quickstep            48731 non-null  float64
 48  ismir04_rhythm_Rumba-American       48731 non-null  float64
 49  ismir04_rhythm_Rumba-International  48731 non-null  float64
 50  ismir04_rhythm_Rumba-Misc           48731 non-null  float64
 51  ismir04_rhythm_Samba                48731 non-null  float64
 52  ismir04_rhythm_Tango                48731 non-null  float64
 53  ismir04_rhythm_VienneseWaltz        48731 non-null  float64
 54  ismir04_rhythm_Waltz                48731 non-null  float64
 55  mood_acoustic                       48731 non-null  float64
 56  mood_not_acoustic                   48731 non-null  float64
 57  mood_aggressive                     48731 non-null  float64
 58  mood_not_aggressive                 48731 non-null  float64
 59  mood_electronic                     48731 non-null  float64
 60  mood_not_electronic                 48731 non-null  float64
 61  mood_happy                          48731 non-null  float64
 62  mood_not_happy                      48731 non-null  float64
 63  mood_party                          48731 non-null  float64
 64  mood_not_party                      48731 non-null  float64
 65  mood_relaxed                        48731 non-null  float64
 66  mood_not_relaxed                    48731 non-null  float64
 67  mood_sad                            48731 non-null  float64
 68  mood_not_sad                        48731 non-null  float64
 69  mood_mirex1                         48731 non-null  float64
 70  mood_mirex2                         48731 non-null  float64
 71  mood_mirex3                         48731 non-null  float64
 72  mood_mirex4                         48731 non-null  float64
 73  mood_mirex5                         48731 non-null  float64
 74  spotify_url                         41259 non-null  object
 75  album_name                          41256 non-null  object
 76  album_release_date                  41259 non-null  object
 77  duration_ms                         41259 non-null  float64
 78  popularity                          41259 non-null  float64
 79  language                            48278 non-null  object
 80  playlist_ids                        0 non-null      float64
 81  playlists_names                     0 non-null      float64
 82  combined_genres                     0 non-null      float64
 83  lyrics                              48720 non-null  object
 84  genres                              48731 non-null  object
 85  tags                                48731 non-null  object
dtypes: float64(76), object(10)
memory usage: 32.0+ MB
None
          danceable  not_danceable          male        female  timbre_bright  \
count  48731.000000   48731.000000  48731.000000  48731.000000   48731.000000
mean       0.458727       0.541273      0.441272      0.558728       0.536215
std        0.378428       0.378428      0.319538      0.319538       0.397993
min        0.000000       0.000000      0.000000      0.000000       0.000000
25%        0.069000       0.139000      0.128000      0.350000       0.084000
50%        0.403000       0.597000      0.437000      0.563000       0.612000
75%        0.861000       0.931000      0.650000      0.872000       0.952000
max        1.000000       1.000000      1.000000      1.000000       1.000000

        timbre_dark         tonal        atonal  instrumental         voice  \
count  48731.000000  48731.000000  48731.000000  48731.000000  48731.000000
mean       0.463785      0.490558      0.509442      0.667992      0.332008
std        0.397993      0.379358      0.379358      0.361516      0.361516
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.048000      0.079000      0.111000      0.357000      0.024000
50%        0.388000      0.500000      0.500000      0.849000      0.151000
75%        0.916000      0.889000      0.921000      0.976000      0.643000
max        1.000000      1.000000      1.000000      1.000000      1.000000

       dortmund_alternative  dortmund_blues  dortmund_electronic  \
count          48731.000000    48731.000000         48731.000000
mean               0.073582        0.036499             0.735505
std                0.092019        0.069653             0.324554
min                0.000000        0.000000             0.000000
25%                0.004000        0.000000             0.513000
50%                0.034000        0.008000             0.914000
75%                0.115000        0.046000             0.993000
max                0.690000        0.947000             1.000000

       dortmund_folkcountry  dortmund_funksoulrnb  dortmund_jazz  \
count          48731.000000          48731.000000   48731.000000
mean               0.064479              0.003867       0.013134
std                0.120742              0.006719       0.035537
min                0.000000              0.000000       0.000000
25%                0.001000              0.000000       0.000000
50%                0.012000              0.001000       0.003000
75%                0.069000              0.006000       0.015000
max                0.892000              0.236000       0.979000

       dortmund_pop  dortmund_raphiphop  dortmund_rock  electronic_ambient  \
count  48731.000000        48731.000000   48731.000000        48731.000000
mean       0.008684            0.004125       0.059972            0.476237
std        0.015027            0.026288       0.124584            0.256344
min        0.000000            0.000000       0.000000            0.001000
25%        0.000000            0.000000       0.001000            0.265000
50%        0.001000            0.001000       0.008000            0.453000
75%        0.012000            0.004000       0.060000            0.681000
max        0.491000            0.986000       0.952000            0.998000

       electronic_dnb  electronic_house  electronic_techno  electronic_trance  \
count    48731.000000      48731.000000       48731.000000       48731.000000
mean         0.042217          0.145795           0.025375           0.310374
std          0.070015          0.137271           0.038323           0.252500
min          0.000000          0.000000           0.000000           0.000000
25%          0.011000          0.050000           0.011000           0.087000
50%          0.024000          0.102000           0.018000           0.251000
75%          0.046000          0.195000           0.027000           0.493000

In [20]:
# ver .shape del df
print(df.shape)

(48731, 86)

In [21]:
# Verificar valores nulos
print(df.isnull().sum())

song_name                                 0
artist_name                               0
recording_id                              0
danceable                                 0
not_danceable                             0
male                                      0
female                                    0
timbre_bright                             0
timbre_dark                               0
tonal                                     0
atonal                                    0
instrumental                              0
voice                                     0
dortmund_alternative                      0
dortmund_blues                            0
dortmund_electronic                       0
dortmund_folkcountry                      0
dortmund_funksoulrnb                      0
dortmund_jazz                             0
dortmund_pop                              0
dortmund_raphiphop                        0
dortmund_rock                             0
electronic_ambient                        0
electronic_dnb                            0
electronic_house                          0
electronic_techno                         0
electronic_trance                         0
rosamerica_cla                            0
rosamerica_dan                            0
rosamerica_hip                            0
rosamerica_jaz                            0
rosamerica_pop                            0
rosamerica_rhy                            0
rosamerica_roc                            0
rosamerica_spe                            0
tzanetakis_blu                            0
tzanetakis_cla                            0
tzanetakis_cou                            0
tzanetakis_dis                            0
tzanetakis_hip                            0
tzanetakis_jaz                            0
tzanetakis_met                            0
tzanetakis_pop                            0
tzanetakis_reg                            0
tzanetakis_roc                            0
ismir04_rhythm_ChaChaCha                  0
ismir04_rhythm_Jive                       0
ismir04_rhythm_Quickstep                  0
ismir04_rhythm_Rumba-American             0
ismir04_rhythm_Rumba-International        0
ismir04_rhythm_Rumba-Misc                 0
ismir04_rhythm_Samba                      0
ismir04_rhythm_Tango                      0
ismir04_rhythm_VienneseWaltz              0
ismir04_rhythm_Waltz                      0
mood_acoustic                             0
mood_not_acoustic                         0
mood_aggressive                           0
mood_not_aggressive                       0
mood_electronic                           0
mood_not_electronic                       0
mood_happy                                0
mood_not_happy                            0
mood_party                                0
mood_not_party                            0
mood_relaxed                              0
mood_not_relaxed                          0
mood_sad                                  0
mood_not_sad                              0
mood_mirex1                               0
mood_mirex2                               0
mood_mirex3                               0
mood_mirex4                               0
mood_mirex5                               0
spotify_url                            7472
album_name                             7475
album_release_date                     7472
duration_ms                            7472
popularity                             7472
language                                453
playlist_ids                          48731
playlists_names                       48731
combined_genres                       48731
lyrics                                   11
genres                                    0
tags                                      0
dtype: int64

In [10]:
# ver columnas y filas completas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [10]:
import requests

API_KEY = "dfb554efa71da7f64ae6a8ff51136a5c"
ARTIST = "Chicos Aventura"

url = f"https://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist={ARTIST}&api_key={API_KEY}&format=json"
response = requests.get(url)
data = response.json()

# Verificar si la clave "tags" existe antes de acceder
genres = []
if "artist" in data and "tags" in data["artist"]:
    genres = [tag["name"] for tag in data["artist"]["tags"].get("tag", [])]

if genres:
    print(f"Géneros encontrados: {genres}")
else:
    print("No hay géneros disponibles para este artista en Last.fm.")

Géneros encontrados: ['Enrique Iglesias', 'julio iglesias', 'juan gabriel', 'terricolas', 'CARLOS MATA']

In [12]:
df.sample(10)

,song_name,artist_name,recording_id,danceable,not_danceable,male,female,timbre_bright,timbre_dark,tonal,atonal,instrumental,voice,dortmund_alternative,dortmund_blues,dortmund_electronic,dortmund_folkcountry,dortmund_funksoulrnb,dortmund_jazz,dortmund_pop,dortmund_raphiphop,dortmund_rock,electronic_ambient,electronic_dnb,electronic_house,electronic_techno,electronic_trance,rosamerica_cla,rosamerica_dan,rosamerica_hip,rosamerica_jaz,rosamerica_pop,rosamerica_rhy,rosamerica_roc,rosamerica_spe,tzanetakis_blu,tzanetakis_cla,tzanetakis_cou,tzanetakis_dis,tzanetakis_hip,tzanetakis_jaz,tzanetakis_met,tzanetakis_pop,tzanetakis_reg,tzanetakis_roc,ismir04_rhythm_ChaChaCha,ismir04_rhythm_Jive,ismir04_rhythm_Quickstep,ismir04_rhythm_Rumba-American,ismir04_rhythm_Rumba-International,ismir04_rhythm_Rumba-Misc,ismir04_rhythm_Samba,ismir04_rhythm_Tango,ismir04_rhythm_VienneseWaltz,ismir04_rhythm_Waltz,mood_acoustic,mood_not_acoustic,mood_aggressive,mood_not_aggressive,mood_electronic,mood_not_electronic,mood_happy,mood_not_happy,mood_party,mood_not_party,mood_relaxed,mood_not_relaxed,mood_sad,mood_not_sad,mood_mirex1,mood_mirex2,mood_mirex3,mood_mirex4,mood_mirex5,spotify_url,album_name,album_release_date,duration_ms,popularity,language,playlist_ids,playlists_names,combined_genres,lyrics,genres,tags,translated_lyrics
11509,Kosmos,Valensia,d4b86fd5-6df4-4fae-81ea-43f183ec58fa,0.169,0.831,0.722,0.278,0.337,0.663,0.991,0.009,0.115,0.885,0.000,0.000,0.999,0.000,0.000,0.000,0.000,0.000,0.000,0.644,0.006,0.099,0.010,0.241,0.183,0.018,0.052,0.452,0.108,0.143,0.027,0.017,0.063,0.035,0.104,0.078,0.157,0.314,0.045,0.063,0.063,0.078,0.001,0.001,0.000,0.000,0.000,0.000,0.000,0.001,0.996,0.000,0.456,0.544,0.052,0.948,0.520,0.480,0.882,0.118,0.213,0.787,0.881,0.119,0.539,0.461,0.089,0.123,0.253,0.097,0.438,https://open.spotify.com/track/3YBHJfv0txNeDcf...,Valensia 2,1996-01-01,260093.0,2.0,en,NaN,NaN,NaN,[Verse I:] Yesterday a star was born Universe ...,"rock, Symphonic Rock, Progressive rock, dutch,...","rock, Queen, melodic, dutch, valentine",NaN
13537,This Time,Dwight Yoakam,65496492-06dd-4219-816b-7de417cc52c2,0.900,0.100,0.591,0.409,0.945,0.055,0.421,0.579,0.938,0.062,0.086,0.054,0.573,0.176,0.007,0.019,0.017,0.006,0.061,0.533,0.041,0.240,0.022,0.165,0.012,0.086,0.130,0.023,0.417,0.241,0.085,0.006,0.061,0.034,0.076,0.061,0.151,0.303,0.043,0.060,0.061,0.151,0.491,0.078,0.017,0.029,0.051,0.015,0.054,0.152,0.100,0.012,0.286,0.714,0.007,0.993,0.413,0.587,0.575,0.425,0.371,0.629,0.030,0.970,0.536,0.464,0.113,0.237,0.418,0.189,0.043,https://open.spotify.com/track/230X3FvKaHbUHbo...,This Time,1993-03-12,238160.0,27.0,en,NaN,NaN,NaN,This time Is the last time That'll I'll ever c...,"country, Honky Tonk, Alt-country, singer-songw...","country, 80s, singer-songwriter, classic count...",NaN
5959,Internado De Señoritas,Autobus,5580f31b-0308-4d4b-b7dd-9ec7b30eff92,0.394,0.606,0.325,0.675,0.986,0.014,0.938,0.062,0.500,0.500,0.136,0.061,0.446,0.251,0.006,0.012,0.019,0.005,0.064,0.513,0.014,0.116,0.015,0.342,0.140,0.056,0.041,0.083,0.253,0.264,0.136,0.026,0.063,0.035,0.078,0.105,0.157,0.314,0.045,0.063,0.063,0.078,0.182,0.196,0.030,0.040,0.048,0.053,0.047,0.147,0.239,0.019,0.738,0.262,0.032,0.968,0.190,0.810,0.249,0.751,0.700,0.300,0.551,0.449,0.302,0.698,0.257,0.268,0.138,0.185,0.152,https://open.spotify.com/track/6Jl48iiU77tVji3...,Bailando Sobre los Escombros,2012-12-04,148733.0,14.0,es,NaN,NaN,NaN,"Buen día, hermana Vengo a traer mi hija La más...","peruvian, Peru, indie pop, indie rock, under 2...",Unknown,"Good morning, I come to bring my daughter the ..."
23087,Blue Hawaii,Willie Nelson,176f9eb9-3068-4dbe-bafe-fdbdc86f344a,0.012,0.988,0.574,0.426,0.668,0.332,0.177,0.823,0.929,0.071,0.030,0.382,0.033,0.423,0.007,0.049,0.036,0.002,0.039,0.873,0.009,0.104,0.006,0.008,0.021,0.001,0.002,0.221,0.070,0.678,0.003,0.004,0.046,0.035,0.055,0.055,0.068,0.274,0.034,0.091,0.069,0.274,0.034,0.005,0.011,0.038,0.309,0.056,0.017,0.072,0.222,0.236,0.884,0.116,0.000,1.000,0.128,0.872,0.048,0.952,0.016,0.984,0.775,0.225,0.856,0.144,0.117,0.261,0.376,0.225,0.020,https://open.spotify.com/track/3UgkWKTgdykcdbt...,Jack Johnson & Friends: Best Of Kokua Festival...,2012-01-01,197013.0,32.0,en,NaN,NaN,NaN,Night and you And blue Hawaii The night is hea...,"country, folk, singer-songwriter, outlaw count...","elvis presley cover, Soundtrack, cover",NaN
2144,Obscurity Reigns Fields Of Flanders,Ancient Rites,8e4b4568-eb62-4c79-9b0f-7f42d724efca,0.000,1.000,0.553,0.447,0.095,0.905,0.085,0.915,0.987,0.013,0.298,0.033,0.349,0.042,0.005,0.010,0.012,0.003,0.249,0.109,0.048,0.135,0.020,0.689,0.000,0.667,0.016,0.000,0.014,0.002,0.300,0.000,0.063,0.035,0.104,0.078,0.157,0.314,0.045,0.063,0.063,0.078,0.930,0.043,0.001,0.009,0.001,0.001,0.007,0.003,0.006,0.000,0.000,1.000,0.998,0.002,0.725,0.275,0.427,0.573,0.888,0.112,0.091,0.909,0.028,0.972,0.043,0.006,0.008,0.007,0.936,NaN,NaN,NaN,NaN,NaN,en,NaN,NaN,NaN,Blasphemous rites Churches in flames Satanic o...,"black metal, viking metal, folk metal, melodic...",Unknown,NaN
10008,Use Me While You Can,Bruce Cockburn,1e5509b7-cd54-4831-a256-d6984b96c0b9,0.035,0.965,0.115,0.885,0.901,0.099,0.967,0.033,0.072,0.928,0.000,0.000,0.999,0.000,0.000,0.000,0.000,0.000,0.000,0.925,0.001,0.036,0.006,0.032,0.641,0.009,0.021,0.163,0.031,0.081,0.022,0.032,0.057,0.038,0.114,0.057,0.171,0.171,0.049,0.086,0.086,0.171,0.010,0.001,0.001,0.005,0.002,0.005,0.002,0.910,0.061,0.002,0.972,0.028,0.042,0.958,0.258,0.742,0.011,0.989,0.020,0.980,1.000,0.000,0.670,0.330,0.106,0.127,0.325,0.080,0.362,https://open.spotify.com/track/1cbyxYPnfm8Cjtu...,Breakfast In New Orleans Dinner In Timbuktu,1999-01-01,432000.0,5.0,en,NaN,NaN,NaN,[Intro] There's a black and white crow On the ...,"singer-songwriter, Canadian, folk, folk-rock, ...","folkrock, title is a full sentence, folk rock,...",NaN
22481,Rudolph The Red-Nosed Reindeer,Babyface,567837b2-8e6a-4be4-b091-c1f9701f59ed,0.809,0.191,0.981,0.019,0.941,0.059,0.206,0.794,0.851,0.149,0.078,0.054,0.601,0.086,0.019,0.048,0.027,0.009,0.078,0.545,0.045,0.286,0.022,0.102,0.000,0.007,0.019,0.021,0.549,0.399,0.003,0.001,0.069,0.038,0.115,0.069,0.173,0.173,0.049,0.069,0.069,0.173,0.956,0.006,0.003,0.016,0.003,0.002,0.007,0.003,0.002,0.001,0.052,0.948,0.000,1.000,0.588,0.412,0.218,0.782,0.005,0.995,0.809,0.191,0.331,0.669,0.159,0.382,0.100,0.208,0.151,https://open.spotify.com/track/2M5q18leb8MX3Y1...,Christmas With Babyface,1998-10-27,242600.0,22.0,en,NaN,NaN,NaN,"[Verse 1] Rudolph, the red-nosed reindeer Had ...","rnb, soul, male vocalists, pop, rhythm and blues","christmas, rnb, Christmas tag, pop, winter",NaN
7488,Hall of Heads,They Might Be Giants,d27202d8-d97d-44ee-85ed-fc2c78da4bc1,0.000,1.000,0.622,0.378,0.006,0.994,0.000,1.000,0.004,0.996,0.002,0.001,0.991,0.001,0.000,0.003,0.000,0.000,0.002,0.621,0.089,0.155,0.070,0.065,0.026,0.097,0.226,0.034,0.208,0.132,0.226,0.050,0.062,0.034,0.103,0.051,0.154,0.309,0.044,0.077,0.062,0.103,0.950,0.002,0.002,0.005,0.019,0.001,0.006,0.002,0.012,0.000,0.096,0.904,0.000,1.000,0.979,0.021,0.067,0.933,0.000,1.000,0.809,0.191,0.073,0.927,0.077,0.044,0.228,0.031,0.620,https://open.spotify.com/track/6Uq4RQOzQHtpHbJ...,Apollo 18,1992-03-24,171333.0,18.0,en,NaN,NaN,NaN,Here in the hall of heads You look through the...,"alternative, indie, rock, seen live, geek rock","alternative, pop, rock, awesome saxophone, alt...",NaN
723,El Aguacate,Alberto Plaza,617c06ac-71d7-4364-9cea-db47e493d948,0.067,0.933,0.116,0.884,0.123,0.877,0.399,0.601,0.999,0.001,0.286,0.118,0.173,0.202,0.012,0.031,0.016,0.008,0.155,0.950,0.010,0.021,0.008,0.011,0.670,0.007,0.018,0.138,0.040,0.054,0.024,0.048,0.063,0.035,0.104,0.078,0.157,0.314,0.045,0.063,0.063,0.078,0.013,0.001,0.001,0.007,0.001,0.001,0.002,0.919,0.053,0.004,0.923,0.077,0.141,0.859,0.163,0.837,0.915,0.085,0.086,0.914,0.672,0.328,0.795,0.205,0.087,0.054,0.421,0.179,0.259,https://open.spotify.com/track/2gdSYCp2pqliQkt...,Todas las Voces Trova (En Vivo),2020-06-19,173866.0,14.0,es,NaN,NaN,NaN,Tú eres mi amor Mi dicha y mi tesoro Mi solo e...,"spanish, chile, latin, Ballad, singer-songwriter",Unknown,You are my love my joy and my treasure my only...
15306,I Got Over It,Robben Ford,197be2d7-417e-4691-8abf-186050b1d971,0.225,0.775,0.289,0.711,0.910,0.090,0.956,0.044,0.890,0.110,0.112,0.032,0.737,0.052,0.005,0.008,0.009,0.004,0.040,0.564,0.038,0.090,0.010,0.298,0.011,0.021,0.006,0.018,0.254,0.094,0.593,0.004,0.062,0.034,0.103,0.062,0.155,0.311,0.044,0.062,0.062,0.103,0.109,0.369,0.023,0.035,0.026,0.026,0.038,0.066,0.292,0.017,0.132,0.868,0.013,0.987,0.113,0.887,0.805,0.195,0.528,0.472,0.427,0.573,0.314,0.686,0.118,0.105,0.353,0.149,0.275,https://open.spotify.com/track/3NkFZMTwZb9FzWQ...,Talk To Your Daughter,1988,204000.0,13.0,en,NaN,NaN,NaN,I got over it finally got around it I got over...,"blues, blues rock, guitar, jazz, Fusion","rock, blues, blues rock, Rock and Roll, Robben...",NaN

In [13]:
# nulos
df.isnull().sum()

song_name                                 0
artist_name                               0
recording_id                              0
danceable                                 0
not_danceable                             0
male                                      0
female                                    0
timbre_bright                             0
timbre_dark                               0
tonal                                     0
atonal                                    0
instrumental                              0
voice                                     0
dortmund_alternative                      0
dortmund_blues                            0
dortmund_electronic                       0
dortmund_folkcountry                      0
dortmund_funksoulrnb                      0
dortmund_jazz                             0
dortmund_pop                              0
dortmund_raphiphop                        0
dortmund_rock                             0
electronic_ambient                        0
electronic_dnb                            0
electronic_house                          0
electronic_techno                         0
electronic_trance                         0
rosamerica_cla                            0
rosamerica_dan                            0
rosamerica_hip                            0
rosamerica_jaz                            0
rosamerica_pop                            0
rosamerica_rhy                            0
rosamerica_roc                            0
rosamerica_spe                            0
tzanetakis_blu                            0
tzanetakis_cla                            0
tzanetakis_cou                            0
tzanetakis_dis                            0
tzanetakis_hip                            0
tzanetakis_jaz                            0
tzanetakis_met                            0
tzanetakis_pop                            0
tzanetakis_reg                            0
tzanetakis_roc                            0
ismir04_rhythm_ChaChaCha                  0
ismir04_rhythm_Jive                       0
ismir04_rhythm_Quickstep                  0
ismir04_rhythm_Rumba-American             0
ismir04_rhythm_Rumba-International        0
ismir04_rhythm_Rumba-Misc                 0
ismir04_rhythm_Samba                      0
ismir04_rhythm_Tango                      0
ismir04_rhythm_VienneseWaltz              0
ismir04_rhythm_Waltz                      0
mood_acoustic                             0
mood_not_acoustic                         0
mood_aggressive                           0
mood_not_aggressive                       0
mood_electronic                           0
mood_not_electronic                       0
mood_happy                                0
mood_not_happy                            0
mood_party                                0
mood_not_party                            0
mood_relaxed                              0
mood_not_relaxed                          0
mood_sad                                  0
mood_not_sad                              0
mood_mirex1                               0
mood_mirex2                               0
mood_mirex3                               0
mood_mirex4                               0
mood_mirex5                               0
spotify_url                            4881
album_name                             4883
album_release_date                     4881
duration_ms                            4881
popularity                             4881
language                                246
playlist_ids                          27139
playlists_names                       27139
combined_genres                       27139
lyrics                                    4
genres                                    0
tags                                      0
translated_lyrics                     22409
dtype: int64

In [13]:
#ver celdas completas
pd.set_option('display.max_colwidth', None)

COLUMNAS ELIMINADAS

In [9]:
# song_name nulos eliminar
df = df.dropna(subset=['song_name', 'spotify_url'])

In [ ]:
# ejemplos canciones con nulos en lyrics donde se muestre nombre de canción, artista y url
df[df['lyrics'].isnull()][['song_name', 'artist_name', 'spotify_url']].sample(10)

,song_name,artist_name,spotify_url
31219,lets stay together,pat benatar,https://open.spotify.com/track/4AMxLpWKpLms3VodVfZ4eW
39884,we can change the world,the jacksons,https://open.spotify.com/track/2GKrX2P8RFB3HXRzQuTjAx
123751,kiss the girl,brian wilson,https://open.spotify.com/track/5b0Kdt6dGY8kZl4EoAkNU2
34741,for love to come...,tyler lyle,https://open.spotify.com/track/5dIVu9I3qXoDAEvzAcx2ii
89324,i’m going higher,m. ward,https://open.spotify.com/track/37UEhGvbvk057sfj8L61R8
95525,whatever makes you happy,alessi's ark,https://open.spotify.com/track/2Y03fbw8IOItgTaoQlmHb8
134431,breathe,through fire,https://open.spotify.com/track/6clbkZDwF3JkTUCkSSNMWP
59202,nous aussi,bigflo & oli,https://open.spotify.com/track/7a3CKEGVISxMGY3WUfdvs4
143995,white noise,lauren o'connell,https://open.spotify.com/track/1fBMNDYgg3BdR9G7VBzzuX
155460,power back,mary j. blige,https://open.spotify.com/track/3xv5vmRlRvuBpOHtKmhEFr

In [7]:
# Cargar el archivo CSV si 'df' no está definido
if 'df' not in locals():
	file_path = r'C:\Users\solan\MoodTune\data\procesando\df_80-200_p2_spoty.csv'
	df = pd.read_csv(file_path)

# Quitar saltos de línea en la columna 'lyrics'
df['lyrics'] = df['lyrics'].str.replace('\n', ' ', regex=True)

# Guardar el DataFrame modificado en un nuevo archivo CSV
output_path = r'C:\Users\solan\MoodTune\data\procesando\df_80-200_p2_spoty.csv'
df.to_csv(output_path, index=False)
# C:\Users\solan\MoodTune\data\procesando\df_80-200_p2_spoty.csv quitar saltos de linea en lyrics