In [ ]:
import pandas as pd

# Cargar el archivo CSV
file_path = r'C:\Users\solan\MoodTune\data\for_spoty2.csv'
df = pd.read_csv(file_path)

# Mostrar las primeras filas del DataFrame
print(df.head())

# Información general del DataFrame
print(df.info())

# Descripción estadística de las columnas numéricas
print(df.describe())

                  artist_name                    song_name  \
0       morning teleportation                  banjo disco
1                    don omar  los hombres tienen la culpa
2                   blowsight                invisible ink
3  the red jumpsuit apparatus             wide is the gate
4              chasing safety             brand new prison

                           recording_id  danceable  not_danceable   male  \
0  f8480eff-db6b-4272-98ef-281e3ed5ab95      0.883          0.117  0.015
1  d8dee02d-ef6e-4d2f-91db-6b34c61eb69d      0.928          0.072  0.000
2  20c60ccf-ab87-4296-8d56-ce83084fa2ea      0.961          0.039  0.044
3  0a60eac7-0c81-461c-a9e6-64a006e08253      0.759          0.241  0.079
4  a5cff947-46c3-4614-aeb7-84038293419c      0.394          0.606  0.240

   female  timbre_bright  timbre_dark  tonal  ...  \
0   0.985          0.964        0.036  0.974  ...
1   1.000          0.986        0.014  0.391  ...
2   0.956          0.006        0.994  0.034  ...
3   0.921          0.112        0.888  0.984  ...
4   0.760          0.027        0.973  0.232  ...

                                              lyrics  spotify_url  album_name  \
0  cant remember how we got here now but its so r...          NaN         NaN
1  si mi culpabilidad es por una razón justa si e...          NaN         NaN
2  did you know that i knew all the things that y...          NaN         NaN
3  wide is the gate lyrics were not the weak or t...          NaN         NaN
4  this is a lonely road im not sure where it goe...          NaN         NaN

   album_release_date  duration_ms  popularity  language  genres  tags  views
0                 NaN          NaN         NaN        en     NaN   NaN    NaN
1                 NaN          NaN         NaN        es     NaN   NaN    NaN
2                 NaN          NaN         NaN        en     NaN   NaN    NaN
3                 NaN          NaN         NaN        en     NaN   NaN    NaN
4                 NaN          NaN         NaN        en     NaN   NaN    NaN

[5 rows x 85 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12656 entries, 0 to 12655
Data columns (total 85 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   artist_name                         12656 non-null  object
 1   song_name                           12656 non-null  object
 2   recording_id                        12656 non-null  object
 3   danceable                           12656 non-null  float64
 4   not_danceable                       12656 non-null  float64
 5   male                                12656 non-null  float64
 6   female                              12656 non-null  float64
 7   timbre_bright                       12656 non-null  float64
 8   timbre_dark                         12656 non-null  float64
 9   tonal                               12656 non-null  float64
 10  atonal                              12656 non-null  float64
 11  instrumental                        12656 non-null  float64
 12  voice                               12656 non-null  float64
 13  dortmund_alternative                12656 non-null  float64
 14  dortmund_blues                      12656 non-null  float64
 15  dortmund_electronic                 12656 non-null  float64
 16  dortmund_folkcountry                12656 non-null  float64
 17  dortmund_funksoulrnb                12656 non-null  float64
 18  dortmund_jazz                       12656 non-null  float64
 19  dortmund_pop                        12656 non-null  float64
 20  dortmund_raphiphop                  12656 non-null  float64
 21  dortmund_rock                       12656 non-null  float64
 22  electronic_ambient                  12656 non-null  float64
 23  electronic_dnb                      12656 non-null  float64
 24  electronic_house                    12656 non-null  float64
 25  electronic_techno                   12656 non-null  float64
 26  electronic_trance                   12656 non-null  float64
 27  rosamerica_cla                      12656 non-null  float64
 28  rosamerica_dan                      12656 non-null  float64
 29  rosamerica_hip                      12656 non-null  float64
 30  rosamerica_jaz                      12656 non-null  float64
 31  rosamerica_pop                      12656 non-null  float64
 32  rosamerica_rhy                      12656 non-null  float64
 33  rosamerica_roc                      12656 non-null  float64
 34  rosamerica_spe                      12656 non-null  float64
 35  tzanetakis_blu                      12656 non-null  float64
 36  tzanetakis_cla                      12656 non-null  float64
 37  tzanetakis_cou                      12656 non-null  float64
 38  tzanetakis_dis                      12656 non-null  float64
 39  tzanetakis_hip                      12656 non-null  float64
 40  tzanetakis_jaz                      12656 non-null  float64
 41  tzanetakis_met                      12656 non-null  float64
 42  tzanetakis_pop                      12656 non-null  float64
 43  tzanetakis_reg                      12656 non-null  float64
 44  tzanetakis_roc                      12656 non-null  float64
 45  ismir04_rhythm_ChaChaCha            12656 non-null  float64
 46  ismir04_rhythm_Jive                 12656 non-null  float64
 47  ismir04_rhythm_Quickstep            12656 non-null  float64
 48  ismir04_rhythm_Rumba-American       12656 non-null  float64
 49  ismir04_rhythm_Rumba-International  12656 non-null  float64
 50  ismir04_rhythm_Rumba-Misc           12656 non-null  float64
 51  ismir04_rhythm_Samba                12656 non-null  float64
 52  ismir04_rhythm_Tango                12656 non-null  float64
 53  ismir04_rhythm_VienneseWaltz        12656 non-null  float64
 54  ismir04_rhythm_Waltz                12656 non-null  float64
 55  mood_acoustic                       12656 non-null  float64
 56  mood_not_acoustic                   12656 non-null  float64
 57  mood_aggressive                     12656 non-null  float64
 58  mood_not_aggressive                 12656 non-null  float64
 59  mood_electronic                     12656 non-null  float64
 60  mood_not_electronic                 12656 non-null  float64
 61  mood_happy                          12656 non-null  float64
 62  mood_not_happy                      12656 non-null  float64
 63  mood_party                          12656 non-null  float64
 64  mood_not_party                      12656 non-null  float64
 65  mood_relaxed                        12656 non-null  float64
 66  mood_not_relaxed                    12656 non-null  float64
 67  mood_sad                            12656 non-null  float64
 68  mood_not_sad                        12656 non-null  float64
 69  mood_mirex1                         12656 non-null  float64
 70  mood_mirex2                         12656 non-null  float64
 71  mood_mirex3                         12656 non-null  float64
 72  mood_mirex4                         12656 non-null  float64
 73  mood_mirex5                         12656 non-null  float64
 74  genre                               6999 non-null   object
 75  lyrics                              12656 non-null  object
 76  spotify_url                         0 non-null      float64
 77  album_name                          0 non-null      float64
 78  album_release_date                  0 non-null      float64
 79  duration_ms                         0 non-null      float64
 80  popularity                          0 non-null      float64
 81  language                            12527 non-null  object
 82  genres                              0 non-null      float64
 83  tags                                0 non-null      float64
 84  views                               0 non-null      float64
dtypes: float64(79), object(6)
memory usage: 8.2+ MB
None
          danceable  not_danceable          male        female  timbre_bright  \
count  12656.000000   12656.000000  12656.000000  12656.000000   12656.000000
mean       0.504065       0.495935      0.498706      0.501294       0.487251
std        0.388809       0.388809      0.334652      0.334652       0.389156
min        0.000000       0.000000      0.000000      0.000000       0.000000
25%        0.092000       0.068000      0.172000      0.185000       0.068750
50%        0.500000       0.500000      0.514000      0.486000       0.471000
75%        0.932000       0.908000      0.815000      0.828000       0.907000
max        1.000000       1.000000      1.000000      1.000000       1.000000

        timbre_dark         tonal        atonal  instrumental         voice  \
count  12656.000000  12656.000000  12656.000000  12656.000000  12656.000000
mean       0.512749      0.444271      0.555729      0.668550      0.331450
std        0.389156      0.363851      0.363851      0.348444      0.348444
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.093000      0.072000      0.182000      0.371000      0.028000
50%        0.529000      0.390500      0.609500      0.830000      0.170000
75%        0.931250      0.818000      0.928000      0.972000      0.629000
max        1.000000      1.000000      1.000000      1.000000      1.000000

       ...   mood_mirex4   mood_mirex5  spotify_url  album_name  \
count  ...  12656.000000  12656.000000          0.0         0.0
mean   ...      0.140536      0.343068          NaN         NaN
std    ...      0.083901      0.241724          NaN         NaN
min    ...      0.002000      0.003000          NaN         NaN
25%    ...      0.074000      0.126000          NaN         NaN
50%    ...      0.129500      0.299000          NaN         NaN
75%    ...      0.192000      0.555000          NaN         NaN
max    ...      0.532000      0.962000          NaN         NaN

       album_release_date  duration_ms  popularity  genres  tags  views
count                 0.0          0.0         0.0     0.0   0.0    0.0
mean                  NaN          NaN         NaN     NaN   NaN    NaN
std                   NaN          NaN         NaN     NaN   NaN    NaN
min                   NaN          NaN         NaN     NaN   NaN    NaN
25%                   NaN          NaN         NaN     NaN   NaN    NaN
50%                   NaN          NaN         NaN     NaN   NaN    NaN
75%                   NaN          NaN         NaN     NaN   NaN    NaN
max                   NaN          NaN         NaN     NaN   NaN    NaN

[8 rows x 79 columns]
artist_name          0
song_name            0
recording_id         0
danceable            0
not_danceable        0
                 ...
popularity       12656
language           129
genres           12656
tags             12656
views            12656
Length: 85, dtype: int64

In [5]:
# Verificar valores nulos
print(df.isnull().sum())

artist_name                               0
song_name                                 0
recording_id                              0
danceable                                 0
not_danceable                             0
male                                      0
female                                    0
timbre_bright                             0
timbre_dark                               0
tonal                                     0
atonal                                    0
instrumental                              0
voice                                     0
dortmund_alternative                      0
dortmund_blues                            0
dortmund_electronic                       0
dortmund_folkcountry                      0
dortmund_funksoulrnb                      0
dortmund_jazz                             0
dortmund_pop                              0
dortmund_raphiphop                        0
dortmund_rock                             0
electronic_ambient                        0
electronic_dnb                            0
electronic_house                          0
electronic_techno                         0
electronic_trance                         0
rosamerica_cla                            0
rosamerica_dan                            0
rosamerica_hip                            0
rosamerica_jaz                            0
rosamerica_pop                            0
rosamerica_rhy                            0
rosamerica_roc                            0
rosamerica_spe                            0
tzanetakis_blu                            0
tzanetakis_cla                            0
tzanetakis_cou                            0
tzanetakis_dis                            0
tzanetakis_hip                            0
tzanetakis_jaz                            0
tzanetakis_met                            0
tzanetakis_pop                            0
tzanetakis_reg                            0
tzanetakis_roc                            0
ismir04_rhythm_ChaChaCha                  0
ismir04_rhythm_Jive                       0
ismir04_rhythm_Quickstep                  0
ismir04_rhythm_Rumba-American             0
ismir04_rhythm_Rumba-International        0
ismir04_rhythm_Rumba-Misc                 0
ismir04_rhythm_Samba                      0
ismir04_rhythm_Tango                      0
ismir04_rhythm_VienneseWaltz              0
ismir04_rhythm_Waltz                      0
mood_acoustic                             0
mood_not_acoustic                         0
mood_aggressive                           0
mood_not_aggressive                       0
mood_electronic                           0
mood_not_electronic                       0
mood_happy                                0
mood_not_happy                            0
mood_party                                0
mood_not_party                            0
mood_relaxed                              0
mood_not_relaxed                          0
mood_sad                                  0
mood_not_sad                              0
mood_mirex1                               0
mood_mirex2                               0
mood_mirex3                               0
mood_mirex4                               0
mood_mirex5                               0
genre                                  5657
lyrics                                    0
spotify_url                           12656
album_name                            12656
album_release_date                    12656
duration_ms                           12656
popularity                            12656
language                                129
genres                                12656
tags                                  12656
views                                 12656
dtype: int64

In [4]:
# ver columnas y filas completas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [10]:
import requests

API_KEY = "dfb554efa71da7f64ae6a8ff51136a5c"
ARTIST = "Chicos Aventura"

url = f"https://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist={ARTIST}&api_key={API_KEY}&format=json"
response = requests.get(url)
data = response.json()

# Verificar si la clave "tags" existe antes de acceder
genres = []
if "artist" in data and "tags" in data["artist"]:
    genres = [tag["name"] for tag in data["artist"]["tags"].get("tag", [])]

if genres:
    print(f"Géneros encontrados: {genres}")
else:
    print("No hay géneros disponibles para este artista en Last.fm.")

Géneros encontrados: ['Enrique Iglesias', 'julio iglesias', 'juan gabriel', 'terricolas', 'CARLOS MATA']

In [ ]:
df.sample(10)

,artist_name,song_name,recording_id,danceable,not_danceable,male,female,timbre_bright,timbre_dark,tonal,atonal,instrumental,voice,dortmund_alternative,dortmund_blues,dortmund_electronic,dortmund_folkcountry,dortmund_funksoulrnb,dortmund_jazz,dortmund_pop,dortmund_raphiphop,dortmund_rock,electronic_ambient,electronic_dnb,electronic_house,electronic_techno,electronic_trance,rosamerica_cla,rosamerica_dan,rosamerica_hip,rosamerica_jaz,rosamerica_pop,rosamerica_rhy,rosamerica_roc,rosamerica_spe,tzanetakis_blu,tzanetakis_cla,tzanetakis_cou,tzanetakis_dis,tzanetakis_hip,tzanetakis_jaz,tzanetakis_met,tzanetakis_pop,tzanetakis_reg,tzanetakis_roc,ismir04_rhythm_ChaChaCha,ismir04_rhythm_Jive,ismir04_rhythm_Quickstep,ismir04_rhythm_Rumba-American,ismir04_rhythm_Rumba-International,ismir04_rhythm_Rumba-Misc,ismir04_rhythm_Samba,ismir04_rhythm_Tango,ismir04_rhythm_VienneseWaltz,ismir04_rhythm_Waltz,mood_acoustic,mood_not_acoustic,mood_aggressive,mood_not_aggressive,mood_electronic,mood_not_electronic,mood_happy,mood_not_happy,mood_party,mood_not_party,mood_relaxed,mood_not_relaxed,mood_sad,mood_not_sad,mood_mirex1,mood_mirex2,mood_mirex3,mood_mirex4,mood_mirex5,lyrics,spotify_url,album_name,album_release_date,duration_ms,popularity,language,views,track_uri,playlist_ids,positions,playlists_names,combined_genres,translated_lyrics,processed_lyrics
55392,baptiste giabiconi,je te aime,59b143a6-36ef-407b-bd96-c877be0721e5,0.829,0.171,0.000,1.000,0.930,0.070,0.986,0.014,0.987,0.013,0.193,0.050,0.517,0.129,0.006,0.028,0.017,0.004,0.055,0.652,0.016,0.094,0.008,0.230,0.009,0.057,0.016,0.112,0.569,0.185,0.040,0.011,0.063,0.035,0.104,0.078,0.157,0.314,0.045,0.063,0.063,0.078,0.129,0.075,0.025,0.169,0.125,0.033,0.064,0.246,0.114,0.020,0.873,0.127,0.000,1.000,0.454,0.546,0.322,0.678,0.256,0.744,0.705,0.295,0.687,0.313,0.128,0.218,0.373,0.230,0.050,et si je joue de la guitare sur le bord de seine je le fait pour toi et si je saute du haut de la tour eiffel et si je joue de la guitare sur le bord de seine je le fait pour toi et si je saute du haut de la tour eiffel je le fait pour toi en terrasse dun caf je tcris un pome je le fait pour toi si tu veux le pourquoi de cette chanson de ce grain de voix refrain cest parceque je te aime mon amour parceque je te aime pour toujours de plus en plus fort talala talala jamais plus encore talala talala et si je chasse des papillons sur le toit des maisons je le fait pour toi ma vie est un sourire une rvolution quand je pense toi si jcombats des loups des sirnes des dragons je le fais pour toi si tu veux le pourquoi de cette chanson de ce grain de voix refrain cest parceque je te aime mon amour parceque je te aime pour toujours de plus en plus fort talala talala de plus en plus fou talala talala et laisse moi te raconter une histoire humaine comme il y en a des tas il tait une fois une jolie ritournelle crite seulement pour toi refrain parceque je te aime mon amour parceque je te aime pour toujours de plus en plus fort talala talala de plus en plus fous talala talala de plus en plus fort talala talala de plus en plus fou talala talala parceque je te aime mon amour,https://open.spotify.com/track/1NgpdQodhGoKxO0kinLs12,Un homme libre,2014-06-16,166400.0,8.0,fr,NaN,spotify:track:1NgpdQodhGoKxO0kinLs12,[36986],[121],['10/16'],"male vocalists, dance, pop, guys I would fuck, french",and if I play the guitar on the banks of the Seine I do it for you and if I jump from the top of the Eiffel Tower and if I play the guitar on the banks of the Seine I do it for you and if I jump from the top of the Eiffel Tower I do it for you on the terrace of a café I write you a poem I do it for you if you want the reason for this song of this grain of voice refrain it's because I love you my love because I love you forever more and more strongly talala talala never more still talala talal a and if I chase butterflies on the roofs of houses I do it for you my life is a smile a revolution when I think of you if I fight wolves mermaids dragons I do it for you if you want the why of this song of this grain of voice refrain it's because I love you my love because I love you forever stronger and stronger talala talala crazier and crazier talala talala and let me tell you a human story like there are loads once upon a time there was a pretty refrain written only for you chorus because I love you my love because I love you forever stronger and stronger talala talala crazier and crazier talala talala stronger and stronger talala talala crazier and crazier talala talala because I love you my love,and if i play the guitar on the banks of the seine i do it for you and if i jump from the top of the eiffel tower and if i play the guitar on the banks of the seine i do it for you and if i jump from the top of the eiffel tower i do it for you on the terrace of a café i write you a poem i do it for you if you want the reason for this song of this grain of voice refrain its because i love you my love because i love you forever more and more strongly talala talala never more still talala talal a and if i chase butterflies on the roofs of houses i do it for you my life is a smile a revolution when i think of you if i fight wolves mermaids dragons i do it for you if you want the why of this song of this grain of voice refrain its because i love you my love because i love you forever stronger and stronger talala talala crazier and crazier talala talala and let me tell you a human story like there are loads once upon a time there was a pretty refrain written only for you chorus because i love you my love because i love you forever stronger and stronger talala talala crazier and crazier talala talala stronger and stronger talala talala crazier and crazier talala talala because i love you my love
137692,otep,hematopia,df2d03fd-86c6-4466-ab1d-1e79e97b3950,0.995,0.005,0.379,0.621,0.001,0.999,0.012,0.988,0.885,0.115,0.135,0.025,0.706,0.032,0.003,0.037,0.009,0.003,0.051,0.639,0.104,0.108,0.082,0.067,0.021,0.215,0.177,0.148,0.038,0.294,0.064,0.043,0.063,0.035,0.104,0.078,0.157,0.314,0.045,0.063,0.063,0.078,0.567,0.040,0.024,0.090,0.061,0.018,0.084,0.076,0.027,0.013,0.642,0.358,0.175,0.825,0.520,0.480,0.060,0.940,0.141,0.859,0.836,0.164,0.403,0.597,0.262,0.090,0.275,0.113,0.260,verse 1 lizzo whoop i wish a brother whoop get inside my face in the parking lot well i whoop whoop whoop whoop that astronomical ho you comical talking bout you know him where you found him from in the drivethrough got him a number six and you brought him in and gave him your fish sticks he was spilling cause he ate your happy meal and now i think your shine was stealing you got mad your weave start peeling whaaaat thats weird but whats weirder still is the only back you got is the one you lay on now tell me whos to blame huh we just hungry outchea getting meals and paper you just thirsty my dear you worry bout the wrong thing gotta let you you know no respectable female or male or animal get the flow unless the person in charge say so now whos in charge of you a dude in a coupe backing you for the crew boo you whore scaramouche scaramouche better do the fandango nigga i be django shooting you from every angle hurt your feelings and your paycheck got a feeling you wont make it bye hook oops i didnt know you was a wegula oops my bad i didnt know you was a wegula oops my bad i didnt know you was a wegula oh yous a wegula oh yous a wegula oops i didnt know you was a wegula oops my bad i didnt know you was a wegula oops my bad i didnt know you was a wegula oh yous a wegula oh yous a wegula verse 2 sophia eris but im outta control like tell me what you want while youre smoking a blunt and ya turnt eenie meanie constantly rain little did you you know that my girl saw your show on the low bro now you wanna wake up wake up hurry bill murray gotta beat your murray titty with the sauce of a curry season the reason your eyes get blurry better hydrate got that absynthe twentyfirst century miss sick got that blasted boombox this a party and we steppin ladidadi slick serin news gotta make that queen you got three chances you know what i mean the bgc has called this hearing ooh you guilty take it fast get your clothes on the field geppettos got you by the strings and you dancing like i taught him to ooh and you look so smooth wind grind up on a dime and didnt know you be there all the time oops my bad didnt know you be there all the time oops my bad didnt know you be there all the time oops my bad and you still waiting in that line cool how cute no wonder you got an attitude is that you hook oops i didnt know you was a wegula oops my bad i didnt know you was a wegula oops my bad i didnt know you was a wegula oh yous a wegula oh yous a wegula oops i didnt know you was a wegula oops my bad i didnt know you was a wegula oops my bad i didnt know you was a wegula oh yous a wegula oh yous a wegula verse 3 manchita in tha clerb we got so ignorant appetite climbing on some what she last did shit ittybitty tum tum wanna get a little bit o num nums bitty bitty bum bum bum pop wanna get it get it get it dont stop oooh but my fancys just so decadent wanna cop a cop a cota enchilada ricotta salada on top of a cut of charcuterie mercy me merci but oh no no everything is closed except the king of the wegulas castle doors im like womp womp lets go they got wontons or no are there hot sauce that cost extra for that real tomato bububut wait i think im smelling something funny suddenly i caught this wegula talking shit to my buddies whoa whoa whoa slow your roll though recognize the threshold also how could you think that you could prove shit to a hundred proof who you think you talking to we got the absynthe and manchita bout to wegulate this fool hook oops i didnt know you was a wegula oops my bad i didnt know you was a wegula oops my bad i didnt know you was a wegula oh yous a wegula oh yous a wegula oops i didnt know you was a wegula oops my bad i didnt know you was a wegula oops my bad i didnt know you was a wegula oh yous a wegula oh yous a wegula outro i would like a number six ah man these girls ugh why they so loud ugh um if you have something to say you need to say it to us uhh tama excuse me uh he wasnt talking to you he was talkin to me and uh hes a wegula so,https://open.spotify.com/track/7Lhp0gOH6BfWRR7xWjjKYd,hydra,2013-01-22,152373.0,8.0,en,1195.0,spotify:track:6M3ldm7rniOAMGamL68cog,"[15709, 154362, 197925, 25123, 258565, 33254, 335235, 42683, 435816]","[31, 70, 0, 64, 35, 48, 68, 121, 98]","['Femme Fatale', 'wedding - dance', 'Werk', 'Sugar', 'Fun music', 'Running Mix', 'summer sixteen', 'Honey', 'hip hop']","['Nu Metal'] nu metal metal female fronted metal female vocalists death metal, rock n roll, rock n roll",NaN,verse 1 lizzo whoop i wish a brother whoop get inside my face in the parking lot well i whoop whoop whoop whoop that astronomical ho you comical talking bout you know him where you found him from in the drivethrough got him a number six and you brought him in and gave him your fish sticks he was spilling cause he ate your happy meal and now i think your shine was stealing you got mad your weave start peeling whaaaat thats weird but whats weirder still is the only back you got is the one you lay on now tell me whos to blame huh we just hungry outchea getting meals and paper you just thirsty my dear you worry bout the wrong thing gotta let you you know no respectable female or male or animal get the flow unless the person in charge say so now whos in charge of you a dude in a coupe backing you for the crew boo you whore scaramouche scaramouche better do the fandango nigga i be django shooting you from every angle hurt your feelings and your paycheck got a feeling you wont make it bye hook oops i didnt know you was a wegula oops my bad i didnt know you was a wegula oops my bad i didnt know you was a wegula oh yous a wegula oh yous a wegula oops i didnt know you was a wegula oops my bad i didnt know you was a wegula oops my bad i didnt know you was a wegula oh yous a wegula oh yous a wegula verse 2 sophia eris but im outta control like tell me what you want while youre smoking a blunt and ya turnt eenie meanie constantly rain little did you you know that my girl saw your show on the low bro now you wanna wake up wake up hurry bill murray gotta beat your murray titty with the sauce of a curry season the reason your eyes get blurry better hydrate got that absynthe twentyfirst century miss sick got that blasted boombox this a party and we steppin ladidadi slick serin news gotta make that queen you got three chances you know what i mean the bgc has called this hearing ooh you guilty take it fast get your clothes on the field geppettos got you by the strings and you dancing like i taught him to ooh and you look so smooth wind grind up on a dime and didnt know you be there all the time oops my bad didnt know you be there all the time oops my bad didnt know you be there all the time oops my bad and you still waiting in that line cool how cute no wonder you got an attitude is that you hook oops i didnt know you was a wegula oops my bad i didnt know you was a wegula oops my bad i didnt know you was a wegula oh yous a wegula oh yous a wegula oops i didnt know you was a wegula oops my bad i didnt know you was a wegula oops my bad i didnt know you was a wegula oh yous a wegula oh yous a wegula verse 3 manchita in tha clerb we got so ignorant appetite climbing on some what she last did shit ittybitty tum tum wanna get a little bit o num nums bitty bitty bum bum bum pop wanna get it get it get it dont stop oooh but my fancys just so decadent wanna cop a cop a cota enchilada ricotta salada on top of a cut of charcuterie mercy me merci but oh no no everything is closed except the king of the wegulas castle doors im like womp womp lets go they got wontons or no are there hot sauce that cost extra for that real tomato bububut wait i think im smelling something funny suddenly i caught this wegula talking shit to my buddies whoa whoa whoa slow your roll though recognize the threshold also how could you think that you could prove shit to a hundred proof who you think you talking to we got the absynthe and manchita bout to wegulate this fool hook oops i didnt know you was a wegula oops my bad i didnt know you was a wegula oops my bad i didnt know you was a wegula oh yous a wegula oh yous a wegula oops i didnt know you was a wegula oops my bad i didnt know you was a wegula oops my bad i didnt know you was a wegula oh yous a wegula oh yous a wegula outro i would like a number six ah man these girls ugh why they so loud ugh um if you have something to say you need to say it to us uhh tama excuse me uh he wasnt talking to you he was talkin to me and uh hes a wegula so
110767,north mississippi allstars,long haired doney,b3851f41-ceb4-4342-837f-bc7ba12db8b5,0.954,0.046,0.291,0.709,0.133,0.867,0.017,0.983,0.035,0.965,0.004,0.001,0.992,0.001,0.000,0.001,0.000,0.000,0.000,0.278,0.013,0.425,0.043,0.240,0.021,0.449,0.162,0.051,0.087,0.127,0.075,0.028,0.063,0.035,0.104,0.078,0.157,0.314,0.045,0.063,0.063,0.078,0.283,0.079,0.022,0.041,0.053,0.020,0.161,0.279,0.047,0.017,0.160,0.840,0.180,0.820,0.917,0.083,0.141,0.859,0.460,0.540,0.766,0.234,0.170,0.830,0.139,0.154,0.248,0.161,0.298,instrumental intro many years back when the old oaks were young not long after the northmen had come a low and evil deed was done in the dark of the new forest in the dark of the new forest verse 2 from the shores of normandy king william came to albion fair king harold to slay with greed in his heart and his scurrilous claim he took the land for his own he took the land for his own verse 3 now john was a blacksmith an honest old man he raised up his children and he worked with his hands at his familys forge in a patch of land in the dark of the new forest in the dark of the new forest verse 4 king william rode out after his victory to ravage the land in his hunger to thieve for hunting grounds in the wessex trees he took the land for his own he took the land for his own refrain but if you steal the land of an englishman then you shall know this curse your first born sons warm blood will run upon the english earth verse 5 now king williams son was called rufus the red he took up the crown when his father was dead and he rode the hunting grounds in his stead in the dark of the new forest in the dark of the new forest verse 6 but johns curse it called out and walt tyrrell fired low his arrow struck rufus with a sickening blow and he fell from his horse to the ground below and the land took him for its own the land took him for its own refrain so if you steal the land of an englishman then you shall know this curse your first born sons warm blood will run upon the english earth outro many years back when these old oaks were young not long after the northmen had come a low and evil deed was done in the dark of the new forest in the dark of the new forest,https://open.spotify.com/track/3u3Q0byKEropAC3r3p79OC,prayer for peace,2017-06-02,279632.0,23.0,en,646.0,spotify:track:5c48EIJ2qaxUW6ztes7VGx,"[151780, 197285, 476888, 57080]","[14, 178, 96, 80]","['Folk', 'vibin', 'RAD', 'llll']","blues southern rock blues rock jam rock, blues rock, blues rock",NaN,instrumental intro many years back when the old oaks were young not long after the northmen had come a low and evil deed was done in the dark of the new forest in the dark of the new forest verse 2 from the shores of normandy king william came to albion fair king harold to slay with greed in his heart and his scurrilous claim he took the land for his own he took the land for his own verse 3 now john was a blacksmith an honest old man he raised up his children and he worked with his hands at his familys forge in a patch of land in the dark of the new forest in the dark of the new forest verse 4 king william rode out after his victory to ravage the land in his hunger to thieve for hunting grounds in the wessex trees he took the land for his own he took the land for his own refrain but if you steal the land of an englishman then you shall know this curse your first born sons warm blood will run upon the english earth verse 5 now king williams son was called rufus the red he took up the crown when his father was dead and he rode the hunting grounds in his stead in the dark of the new forest in the dark of the new forest verse 6 but johns curse it called out and walt tyrrell fired low his arrow struck rufus with a sickening blow and he fell from his horse to the ground below and the land took him for its own the land took him for its own refrain so if you steal the land of an englishman then you shall know this curse your first born sons warm blood will run upon the english earth outro many years back when these old oaks were young not long after the northmen had come a low and evil deed was done in the dark of the new forest in the dark of the new forest

In [ ]:
# nulos
df.isnull().sum()

artist_name                                0
song_name                                  0
recording_id                               0
danceable                                  0
not_danceable                              0
male                                       0
female                                     0
timbre_bright                              0
timbre_dark                                0
tonal                                      0
atonal                                     0
instrumental                               0
voice                                      0
dortmund_alternative                       0
dortmund_blues                             0
dortmund_electronic                        0
dortmund_folkcountry                       0
dortmund_funksoulrnb                       0
dortmund_jazz                              0
dortmund_pop                               0
dortmund_raphiphop                         0
dortmund_rock                              0
electronic_ambient                         0
electronic_dnb                             0
electronic_house                           0
electronic_techno                          0
electronic_trance                          0
rosamerica_cla                             0
rosamerica_dan                             0
rosamerica_hip                             0
rosamerica_jaz                             0
rosamerica_pop                             0
rosamerica_rhy                             0
rosamerica_roc                             0
rosamerica_spe                             0
tzanetakis_blu                             0
tzanetakis_cla                             0
tzanetakis_cou                             0
tzanetakis_dis                             0
tzanetakis_hip                             0
tzanetakis_jaz                             0
tzanetakis_met                             0
tzanetakis_pop                             0
tzanetakis_reg                             0
tzanetakis_roc                             0
ismir04_rhythm_ChaChaCha                   0
ismir04_rhythm_Jive                        0
ismir04_rhythm_Quickstep                   0
ismir04_rhythm_Rumba-American              0
ismir04_rhythm_Rumba-International         0
ismir04_rhythm_Rumba-Misc                  0
ismir04_rhythm_Samba                       0
ismir04_rhythm_Tango                       0
ismir04_rhythm_VienneseWaltz               0
ismir04_rhythm_Waltz                       0
mood_acoustic                              0
mood_not_acoustic                          0
mood_aggressive                            0
mood_not_aggressive                        0
mood_electronic                            0
mood_not_electronic                        0
mood_happy                                 0
mood_not_happy                             0
mood_party                                 0
mood_not_party                             0
mood_relaxed                               0
mood_not_relaxed                           0
mood_sad                                   0
mood_not_sad                               0
mood_mirex1                                0
mood_mirex2                                0
mood_mirex3                                0
mood_mirex4                                0
mood_mirex5                                0
lyrics                                  2703
spotify_url                                0
album_name                                 0
album_release_date                         0
duration_ms                             4253
popularity                                 0
language                                2697
views                                  43136
track_uri                              62970
playlist_ids                           62982
positions                              62982
playlists_names                        62982
combined_genres                         1166
translated_lyrics                     142663
processed_lyrics                        2740
dtype: int64

In [13]:
#ver celdas completas
pd.set_option('display.max_colwidth', None)

COLUMNAS ELIMINADAS

In [9]:
# song_name nulos eliminar
df = df.dropna(subset=['song_name', 'spotify_url'])

In [ ]:
# ejemplos canciones con nulos en lyrics donde se muestre nombre de canción, artista y url
df[df['lyrics'].isnull()][['song_name', 'artist_name', 'spotify_url']].sample(10)

,song_name,artist_name,spotify_url
31219,lets stay together,pat benatar,https://open.spotify.com/track/4AMxLpWKpLms3VodVfZ4eW
39884,we can change the world,the jacksons,https://open.spotify.com/track/2GKrX2P8RFB3HXRzQuTjAx
123751,kiss the girl,brian wilson,https://open.spotify.com/track/5b0Kdt6dGY8kZl4EoAkNU2
34741,for love to come...,tyler lyle,https://open.spotify.com/track/5dIVu9I3qXoDAEvzAcx2ii
89324,i’m going higher,m. ward,https://open.spotify.com/track/37UEhGvbvk057sfj8L61R8
95525,whatever makes you happy,alessi's ark,https://open.spotify.com/track/2Y03fbw8IOItgTaoQlmHb8
134431,breathe,through fire,https://open.spotify.com/track/6clbkZDwF3JkTUCkSSNMWP
59202,nous aussi,bigflo & oli,https://open.spotify.com/track/7a3CKEGVISxMGY3WUfdvs4
143995,white noise,lauren o'connell,https://open.spotify.com/track/1fBMNDYgg3BdR9G7VBzzuX
155460,power back,mary j. blige,https://open.spotify.com/track/3xv5vmRlRvuBpOHtKmhEFr