In [1]:
import pandas as pd

# Rutas de los archivos
nuevo_path = r"C:\Users\solan\MoodTune\data\procesando\df_80-200_p4_last.csv"
traducidas_path = r"C:\Users\solan\MoodTune\data\procesando\df_80-200_p4_last_traducidas.csv"
final_path = r"C:\Users\solan\MoodTune\data\procesando\df_80-200_final_1.csv"
output_path = r"C:\Users\solan\MoodTune\data\procesando\df_80-200_final_1.csv"

# Cargar archivos
df_nuevo = pd.read_csv(nuevo_path)
df_traducidas = pd.read_csv(traducidas_path)
df_final = pd.read_csv(final_path)

# Unir traducidas con los nuevos datos (por recording_id)
df_nuevo = df_nuevo.set_index('recording_id')
df_traducidas = df_traducidas.set_index('recording_id')

# Añadir translated_lyrics y language si están en traducidas
if 'translated_lyrics' in df_traducidas.columns:
    df_nuevo['translated_lyrics'] = df_traducidas['translated_lyrics']

if 'language' in df_traducidas.columns:
    df_nuevo['language'] = df_traducidas['language']

df_nuevo.reset_index(inplace=True)

# Concatenar el nuevo bloque de datos al final del final existente
df_final_actualizado = pd.concat([df_final, df_nuevo], ignore_index=True)

# Guardar el archivo combinado
df_final_actualizado.to_csv(output_path, index=False)

print(f"✅ Nuevas canciones añadidas y archivo actualizado en: {output_path}")

✅ Nuevas canciones añadidas y archivo actualizado en: C:\Users\solan\MoodTune\data\procesando\df_80-200_final_1.csv

In [2]:
df_final_actualizado.head()

,recording_id,song_name,artist_name,danceable,not_danceable,male,female,timbre_bright,timbre_dark,tonal,...,duration_ms,popularity,language,playlist_ids,playlists_names,combined_genres,lyrics,genres,tags,translated_lyrics
0,2c3486cc-e933-4f05-8dad-442eb3b47d30,Motherfucker,Dwarves,0.037,0.963,0.338,0.662,0.913,0.087,0.340,...,83400.0,35.0,en,NaN,NaN,NaN,Well I'm a motherfucker yes this I must admit ...,"punk, punk rock, seen live, Garage Punk, hardcore","punk, punk rock, Garage Punk, garage, Rock and...",NaN
1,89bb58a7-0bf4-485d-9883-a22ebd5e200d,Holy War,Brainstorm,0.979,0.021,0.330,0.670,0.004,0.996,0.072,...,233333.0,6.0,en,NaN,NaN,NaN,Stir up the nation into war They will believe ...,"Power metal, rock, latvian, heavy metal, seen ...","heavy metal, Power metal, German metal",NaN
2,79a5bc80-9162-45bd-ba51-e6f7b17b5555,Sad But True,Sixpence None the Richer,0.030,0.970,0.331,0.669,0.092,0.908,0.301,...,240374.0,18.0,en,NaN,NaN,NaN,If I could have the words to change To speak i...,"pop, female vocalists, rock, alternative, chri...",heart,NaN
3,1fef8bdd-285a-4948-be33-d994f7d28325,Blue Monday,Lisa Germano,0.000,1.000,0.622,0.378,0.004,0.996,0.000,...,NaN,NaN,en,NaN,NaN,NaN,"So, you're goin' cross Country You're leavin' ...","singer-songwriter, female vocalists, indie, dr...","rock, jazzy",NaN
4,356864f4-4640-404d-944d-235e558c7481,Keep Me In Mind,Cosmicity,0.957,0.043,0.036,0.964,1.000,0.000,0.998,...,253600.0,1.0,en,NaN,NaN,NaN,I have been to places That I dare not go alone...,"synthpop, electronic, ebm, futurepop, synth pop",rainbowfreezepoppers,NaN

In [3]:
df = pd.read_csv(final_path)
df.shape

(70568, 87)

In [38]:
df_final_actualizado.shape

(70568, 87)

In [21]:
# que se vea al impirimir resumen la columna de spotify_url completa
pd.set_option('display.max_colwidth', None)

In [35]:
# ver ejemplo con solo las columnas song_name, artist_name, spotify url, translated lyrics, language
df_final_actualizado[['song_name', 'artist_name', 'spotify_url', 'translated_lyrics', 'language']].sample(10)

,song_name,artist_name,spotify_url,translated_lyrics,language
43104,Grey Walls,Richard Thompson,https://open.spotify.com/track/5tZ78UOq381axo1hBZutT0,NaN,en
24205,One Day This Will All Be Yours,The Wedding Present,https://open.spotify.com/track/4zz6mG59jsY8KS5sabRU4A,NaN,en
49264,It Was Her House That Killed Nessarose,Hannah Fury,https://open.spotify.com/track/7y2VG5CJhrsdqUSg2vUYE7,NaN,en
29781,Adoquines en tu cielo Rosario,Juan Carlos Baglietto,https://open.spotify.com/track/7ylpbbrvnkPq7jFKdSzl7S,Cobbles in your sky and a tram wrapped in the river The frozen past in your name as a rosario woman is like a girlfriend that she did not have in a port where she wanted to be a helmsman emigrants and emigrants polls that in mailboxes bite dust the future is drained in the hands of your yesterday rosario you have a lover body that one feels that I still enjoy even the topic aging in your coast of sirens. Looting asks for bread to grow Rosario has dressed you as a mother that c Ocina What remains not to faint Rosario you will be that female that there is no male who dominates with a stick or two rosary you are like those pots that love you when they feel they are treated with love cobblestones in your sky cobblestones in your sky,es
15993,Nine To Nine Blues,Nuno Mindelis,https://open.spotify.com/track/6nGOUDLqJpuPLPvOmYA1db,NaN,en
68860,Death Party,Waltari,https://open.spotify.com/track/5gT546JuyFmdjGxKqe97Ll,NaN,en
8181,She Never Heard Me Call,Air Supply,https://open.spotify.com/track/5B6bFHXb9fbdeYXa8LeqT8,NaN,en
40416,Cuando Los Sapos Bailen Flamenco,Ella Baila Sola,https://open.spotify.com/track/6L9NMwK94nyeFFJnpHAsqC,"I am so glad to hear your voice although I will finally travel as in your dreams, looking for a place to return and unable to forget what you leave, what you have learned will change the faces, dreams, days and I slowly lose you as a gift that when dirtying, threw who cleaned like a glass after drinking the sweetest drink with a goodby so much fear you're leaving and I get lost to me so much listening to your promises while you know what you think you will return one day, when the toads dance flamenco and I wait for you already see although I do not understand that the toads can stop jumping and dancing away from their puddle because my eyes shine with your face, and now that I do not see you they go out because I prefer that you are by my side that you have nothing you go and I lose like a gift ... you leave and I lose you, I lose you",es
30262,Get Real,Kelly Willis,https://open.spotify.com/track/16dmJuR8d1Gl7TJPIjc6sv,NaN,en
22580,Move This,Ya Kid K,https://open.spotify.com/track/7yVtuQux71kxcRk99ILX5c,NaN,en

In [20]:
# chequear las columnas
df_final_actualizado.columns

Index(['recording_id', 'song_name', 'artist_name', 'danceable',
       'not_danceable', 'male', 'female', 'timbre_bright', 'timbre_dark',
       'tonal', 'atonal', 'instrumental', 'voice', 'dortmund_alternative',
       'dortmund_blues', 'dortmund_electronic', 'dortmund_folkcountry',
       'dortmund_funksoulrnb', 'dortmund_jazz', 'dortmund_pop',
       'dortmund_raphiphop', 'dortmund_rock', 'electronic_ambient',
       'electronic_dnb', 'electronic_house', 'electronic_techno',
       'electronic_trance', 'rosamerica_cla', 'rosamerica_dan',
       'rosamerica_hip', 'rosamerica_jaz', 'rosamerica_pop', 'rosamerica_rhy',
       'rosamerica_roc', 'rosamerica_spe', 'tzanetakis_blu', 'tzanetakis_cla',
       'tzanetakis_cou', 'tzanetakis_dis', 'tzanetakis_hip', 'tzanetakis_jaz',
       'tzanetakis_met', 'tzanetakis_pop', 'tzanetakis_reg', 'tzanetakis_roc',
       'ismir04_rhythm_ChaChaCha', 'ismir04_rhythm_Jive',
       'ismir04_rhythm_Quickstep', 'ismir04_rhythm_Rumba-American',
       'ismir04_rhythm_Rumba-International', 'ismir04_rhythm_Rumba-Misc',
       'ismir04_rhythm_Samba', 'ismir04_rhythm_Tango',
       'ismir04_rhythm_VienneseWaltz', 'ismir04_rhythm_Waltz', 'mood_acoustic',
       'mood_not_acoustic', 'mood_aggressive', 'mood_not_aggressive',
       'mood_electronic', 'mood_not_electronic', 'mood_happy',
       'mood_not_happy', 'mood_party', 'mood_not_party', 'mood_relaxed',
       'mood_not_relaxed', 'mood_sad', 'mood_not_sad', 'mood_mirex1',
       'mood_mirex2', 'mood_mirex3', 'mood_mirex4', 'mood_mirex5',
       'spotify_url', 'album_name', 'album_release_date', 'duration_ms',
       'popularity', 'language', 'playlist_ids', 'playlists_names',
       'combined_genres', 'lyrics', 'genres', 'tags', 'translated_lyrics'],
      dtype='object')

In [28]:
# ver todo el output
pd.set_option('display.max_rows', None)

In [29]:
# ver la salida total de los nulos
df_final_actualizado.isnull().sum()

recording_id                              0
song_name                                 0
artist_name                               0
danceable                                 0
not_danceable                             0
male                                      0
female                                    0
timbre_bright                             0
timbre_dark                               0
tonal                                     0
atonal                                    0
instrumental                              0
voice                                     0
dortmund_alternative                      0
dortmund_blues                            0
dortmund_electronic                       0
dortmund_folkcountry                      0
dortmund_funksoulrnb                      0
dortmund_jazz                             0
dortmund_pop                              0
dortmund_raphiphop                        0
dortmund_rock                             0
electronic_ambient                        0
electronic_dnb                            0
electronic_house                          0
electronic_techno                         0
electronic_trance                         0
rosamerica_cla                            0
rosamerica_dan                            0
rosamerica_hip                            0
rosamerica_jaz                            0
rosamerica_pop                            0
rosamerica_rhy                            0
rosamerica_roc                            0
rosamerica_spe                            0
tzanetakis_blu                            0
tzanetakis_cla                            0
tzanetakis_cou                            0
tzanetakis_dis                            0
tzanetakis_hip                            0
tzanetakis_jaz                            0
tzanetakis_met                            0
tzanetakis_pop                            0
tzanetakis_reg                            0
tzanetakis_roc                            0
ismir04_rhythm_ChaChaCha                  0
ismir04_rhythm_Jive                       0
ismir04_rhythm_Quickstep                  0
ismir04_rhythm_Rumba-American             0
ismir04_rhythm_Rumba-International        0
ismir04_rhythm_Rumba-Misc                 0
ismir04_rhythm_Samba                      0
ismir04_rhythm_Tango                      0
ismir04_rhythm_VienneseWaltz              0
ismir04_rhythm_Waltz                      0
mood_acoustic                             0
mood_not_acoustic                         0
mood_aggressive                           0
mood_not_aggressive                       0
mood_electronic                           0
mood_not_electronic                       0
mood_happy                                0
mood_not_happy                            0
mood_party                                0
mood_not_party                            0
mood_relaxed                              0
mood_not_relaxed                          0
mood_sad                                  0
mood_not_sad                              0
mood_mirex1                               0
mood_mirex2                               0
mood_mirex3                               0
mood_mirex4                               0
mood_mirex5                               0
spotify_url                            7472
album_name                             7479
album_release_date                     7472
duration_ms                            7472
popularity                             7472
language                              18335
playlist_ids                          70568
playlists_names                       70568
combined_genres                       70568
lyrics                                   13
genres                                    0
tags                                      0
translated_lyrics                     58448
dtype: int64

In [31]:
path_chequeo = r"C:\Users\solan\MoodTune\data\procesando\df_80-200_p4.csv"
df_chequeo = pd.read_csv(path_chequeo)
# nulos en language
df_chequeo['language'].isnull().sum()

np.int64(222)

In [33]:
def rellenar_language(row):
    if pd.isna(row['language']):
        resultado = df_chequeo[df_chequeo['recording_id'] == row['recording_id']]
        if not resultado.empty:
            return resultado['language'].values[0]
    return row['language']

df_final_actualizado['language'] = df_final_actualizado.apply(rellenar_language, axis=1)

In [39]:
df_final_actualizado.isnull().sum()

recording_id                              0
song_name                                 0
artist_name                               0
danceable                                 0
not_danceable                             0
male                                      0
female                                    0
timbre_bright                             0
timbre_dark                               0
tonal                                     0
atonal                                    0
instrumental                              0
voice                                     0
dortmund_alternative                      0
dortmund_blues                            0
dortmund_electronic                       0
dortmund_folkcountry                      0
dortmund_funksoulrnb                      0
dortmund_jazz                             0
dortmund_pop                              0
dortmund_raphiphop                        0
dortmund_rock                             0
electronic_ambient                        0
electronic_dnb                            0
electronic_house                          0
electronic_techno                         0
electronic_trance                         0
rosamerica_cla                            0
rosamerica_dan                            0
rosamerica_hip                            0
rosamerica_jaz                            0
rosamerica_pop                            0
rosamerica_rhy                            0
rosamerica_roc                            0
rosamerica_spe                            0
tzanetakis_blu                            0
tzanetakis_cla                            0
tzanetakis_cou                            0
tzanetakis_dis                            0
tzanetakis_hip                            0
tzanetakis_jaz                            0
tzanetakis_met                            0
tzanetakis_pop                            0
tzanetakis_reg                            0
tzanetakis_roc                            0
ismir04_rhythm_ChaChaCha                  0
ismir04_rhythm_Jive                       0
ismir04_rhythm_Quickstep                  0
ismir04_rhythm_Rumba-American             0
ismir04_rhythm_Rumba-International        0
ismir04_rhythm_Rumba-Misc                 0
ismir04_rhythm_Samba                      0
ismir04_rhythm_Tango                      0
ismir04_rhythm_VienneseWaltz              0
ismir04_rhythm_Waltz                      0
mood_acoustic                             0
mood_not_acoustic                         0
mood_aggressive                           0
mood_not_aggressive                       0
mood_electronic                           0
mood_not_electronic                       0
mood_happy                                0
mood_not_happy                            0
mood_party                                0
mood_not_party                            0
mood_relaxed                              0
mood_not_relaxed                          0
mood_sad                                  0
mood_not_sad                              0
mood_mirex1                               0
mood_mirex2                               0
mood_mirex3                               0
mood_mirex4                               0
mood_mirex5                               0
spotify_url                            7472
album_name                             7479
album_release_date                     7472
duration_ms                            7472
popularity                             7472
language                                409
playlist_ids                          70568
playlists_names                       70568
combined_genres                       70568
lyrics                                   13
genres                                    0
tags                                      0
translated_lyrics                     58448
dtype: int64

In [40]:
# volver a guardar el archivo df_final_actualizado
df_final_actualizado.to_csv(output_path, index=False)

In [30]:
# chequear nulos en df_nuevo y ver todo el output
df_nuevo.isnull().sum()

recording_id                              0
song_name                                 0
artist_name                               0
danceable                                 0
not_danceable                             0
male                                      0
female                                    0
timbre_bright                             0
timbre_dark                               0
tonal                                     0
atonal                                    0
instrumental                              0
voice                                     0
dortmund_alternative                      0
dortmund_blues                            0
dortmund_electronic                       0
dortmund_folkcountry                      0
dortmund_funksoulrnb                      0
dortmund_jazz                             0
dortmund_pop                              0
dortmund_raphiphop                        0
dortmund_rock                             0
electronic_ambient                        0
electronic_dnb                            0
electronic_house                          0
electronic_techno                         0
electronic_trance                         0
rosamerica_cla                            0
rosamerica_dan                            0
rosamerica_hip                            0
rosamerica_jaz                            0
rosamerica_pop                            0
rosamerica_rhy                            0
rosamerica_roc                            0
rosamerica_spe                            0
tzanetakis_blu                            0
tzanetakis_cla                            0
tzanetakis_cou                            0
tzanetakis_dis                            0
tzanetakis_hip                            0
tzanetakis_jaz                            0
tzanetakis_met                            0
tzanetakis_pop                            0
tzanetakis_reg                            0
tzanetakis_roc                            0
ismir04_rhythm_ChaChaCha                  0
ismir04_rhythm_Jive                       0
ismir04_rhythm_Quickstep                  0
ismir04_rhythm_Rumba-American             0
ismir04_rhythm_Rumba-International        0
ismir04_rhythm_Rumba-Misc                 0
ismir04_rhythm_Samba                      0
ismir04_rhythm_Tango                      0
ismir04_rhythm_VienneseWaltz              0
ismir04_rhythm_Waltz                      0
mood_acoustic                             0
mood_not_acoustic                         0
mood_aggressive                           0
mood_not_aggressive                       0
mood_electronic                           0
mood_not_electronic                       0
mood_happy                                0
mood_not_happy                            0
mood_party                                0
mood_not_party                            0
mood_relaxed                              0
mood_not_relaxed                          0
mood_sad                                  0
mood_not_sad                              0
mood_mirex1                               0
mood_mirex2                               0
mood_mirex3                               0
mood_mirex4                               0
mood_mirex5                               0
spotify_url                               0
album_name                                4
album_release_date                        0
duration_ms                               0
popularity                                0
language                              18042
playlist_ids                          21837
playlists_names                       21837
combined_genres                       21837
lyrics                                    2
genres                                    0
tags                                      0
translated_lyrics                     18042
dtype: int64