In [1]:
import pandas as pd
import os

In [ ]:
# juntar según el recording_id las columnas 
df1 = pd.read_csv(r'C:\Users\solan\MoodTune\data\procesando\df_80-200_p3_last.csv')
df2 = pd.read_csv(r'C:\Users\solan\MoodTune\data\procesando\df_80-200_p3_2_spoty.csv')

In [10]:
 #Cargar el archivo CSV
file_path = r"C:\Users\solan\Downloads\get_data_from_songs\data\0_get_processed_brainz_spoty.csv"
data = pd.read_csv(file_path)

# Eliminar las columnas especificadas
columns_to_drop = [
 "genres"
]

data_cleaned = data.drop(columns=columns_to_drop, errors='ignore')

# Guardar el archivo modificado
output_path = r"C:\Users\solan\Downloads\get_data_from_songs\data\0_1get_processed_brainz_spoty.csv"
data_cleaned.to_csv(output_path, index=False)

output_path

'C:\\Users\\solan\\Downloads\\get_data_from_songs\\data\\0_1get_processed_brainz_spoty.csv'

In [32]:
# Cargar el archivo CSV
file_path = r"C:\Users\solan\Downloads\get_data_from_songs\data\raw\7_PARTE2.CSV"
data = pd.read_csv(file_path)

# Eliminar las columnas especificadas
columns_to_drop = [
    "lyrics", "spotify_url", "album_name", 
    "album_release_date", "duration_ms", 
    "popularity", "language", "genre", 
    "tags", "views", "genres"
]

data_cleaned = data.drop(columns=columns_to_drop, errors='ignore')

# Guardar el archivo modificado
output_path = r"C:\Users\solan\Downloads\get_data_from_songs\data\Msongs_for_url_7_2.csv"
data_cleaned.to_csv(output_path, index=False)

output_path

'C:\\Users\\solan\\Downloads\\get_data_from_songs\\data\\Msongs_for_url_7_2.csv'

In [35]:
import pandas as pd
import os

# Ruta del archivo CSV grande
file_path = r"C:\Users\solan\Downloads\get_data_from_songs\data\raw\songs_2000_to_2010.csv"

# Tamaño de cada parte (en número de filas)
rows_per_chunk = 5000  # Puedes ajustar este valor según tus necesidades

# Carpeta para guardar los archivos divididos
output_folder = r"C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000"
os.makedirs(output_folder, exist_ok=True)

# Contador para los archivos divididos
file_counter = 1

# Leer y dividir el archivo CSV en partes
try:
    for chunk in pd.read_csv(file_path, chunksize=rows_per_chunk):
        output_file = os.path.join(output_folder, f"genius_songs_part_{file_counter}.csv")
        chunk.to_csv(output_file, index=False)
        print(f"Parte {file_counter} guardada: {output_file}")
        file_counter += 1

    print("División completada.")
except Exception as e:
    print(f"Error al dividir el archivo: {e}")

Parte 1 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_1.csv
Parte 2 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_2.csv
Parte 3 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_3.csv
Parte 4 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_4.csv
Parte 5 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_5.csv
Parte 6 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_6.csv
Parte 7 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_7.csv
Parte 8 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_8.csv
Parte 9 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_9.csv
Parte 10 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_10.csv
Parte 11 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_11.csv
Parte 12 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_12.csv
Parte 13 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_13.csv
Parte 14 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_14.csv
Parte 15 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_15.csv
Parte 16 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_16.csv
Parte 17 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_17.csv
Parte 18 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_18.csv
Parte 19 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_19.csv
Parte 20 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_20.csv
Parte 21 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_21.csv
Parte 22 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_22.csv
Parte 23 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_23.csv
Parte 24 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_24.csv
Parte 25 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_25.csv
Parte 26 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_26.csv
Parte 27 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_27.csv
Parte 28 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_28.csv
Parte 29 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_29.csv
Parte 30 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_30.csv
Parte 31 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_31.csv
Parte 32 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_32.csv
Parte 33 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_33.csv
Parte 34 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_34.csv
Parte 35 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_35.csv
Parte 36 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_36.csv
Parte 37 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_37.csv
Parte 38 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_38.csv
Parte 39 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_39.csv
Parte 40 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_40.csv
Parte 41 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_41.csv
Parte 42 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_42.csv
Parte 43 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_43.csv
Parte 44 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_44.csv
Parte 45 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_45.csv
Parte 46 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_46.csv
Parte 47 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_47.csv
Parte 48 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_48.csv
Parte 49 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_49.csv
Parte 50 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_50.csv
Parte 51 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_51.csv
Parte 52 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_52.csv
Parte 53 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_53.csv
Parte 54 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_54.csv
Parte 55 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_55.csv
Parte 56 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_56.csv
Parte 57 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_57.csv
Parte 58 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_58.csv
Parte 59 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_59.csv
Parte 60 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_60.csv
Parte 61 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_61.csv
Parte 62 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_62.csv
Parte 63 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_63.csv
Parte 64 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_64.csv
Parte 65 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_65.csv
Parte 66 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_66.csv
Parte 67 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_67.csv
Parte 68 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_68.csv
Parte 69 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_69.csv
Parte 70 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_70.csv
Parte 71 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_71.csv
Parte 72 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_72.csv
Parte 73 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_73.csv
Parte 74 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_74.csv
Parte 75 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_75.csv
Parte 76 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_76.csv
Parte 77 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_77.csv
Parte 78 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_78.csv
Parte 79 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_79.csv
Parte 80 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_80.csv
Parte 81 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_81.csv
Parte 82 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_82.csv
Parte 83 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_83.csv
Parte 84 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_84.csv
Parte 85 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_85.csv
Parte 86 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_86.csv
Parte 87 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_87.csv
Parte 88 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_88.csv
Parte 89 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_89.csv
Parte 90 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_90.csv
Parte 91 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_91.csv
Parte 92 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_92.csv
Parte 93 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_93.csv
Parte 94 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_94.csv
Parte 95 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_95.csv
Parte 96 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_96.csv
Parte 97 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_97.csv
Parte 98 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_98.csv
Parte 99 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_99.csv
Parte 100 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_100.csv
Parte 101 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_101.csv
Parte 102 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_102.csv
Parte 103 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_103.csv
Parte 104 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_104.csv
Parte 105 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_105.csv
Parte 106 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_106.csv
Parte 107 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_107.csv
Parte 108 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_108.csv
Parte 109 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_109.csv
Parte 110 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_110.csv
Parte 111 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_111.csv
Parte 112 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_112.csv
Parte 113 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_113.csv
Parte 114 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_114.csv
Parte 115 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_115.csv
Parte 116 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_116.csv
Parte 117 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_117.csv
Parte 118 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_118.csv
Parte 119 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_119.csv
Parte 120 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_120.csv
Parte 121 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_121.csv
Parte 122 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_122.csv
Parte 123 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_123.csv
Parte 124 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_124.csv
Parte 125 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_125.csv
Parte 126 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_126.csv
Parte 127 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_127.csv
Parte 128 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_128.csv
Parte 129 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_129.csv
Parte 130 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_130.csv
Parte 131 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_131.csv
Parte 132 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_132.csv
Parte 133 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_133.csv
Parte 134 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_134.csv
Parte 135 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_135.csv
Parte 136 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_136.csv
Parte 137 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_137.csv
Parte 138 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_138.csv
Parte 139 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_139.csv
Parte 140 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_140.csv
Parte 141 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_141.csv
Parte 142 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_142.csv
Parte 143 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_143.csv
Parte 144 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_144.csv
Parte 145 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_145.csv
Parte 146 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_146.csv
Parte 147 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_147.csv
Parte 148 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_148.csv
Parte 149 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_149.csv
Parte 150 guardada: C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\part1_5000\genius_songs_part_150.csv
División completada.

In [28]:
import pandas as pd

# Ruta del archivo dividido
file_path = r"C:\Users\solan\Downloads\get_data_from_songs\data\processed\split_files\genius_songs_part_1.csv"

# Cargar la décima parte
ids_part1 = pd.read_csv(file_path)

# Ver las primeras filas
print(ids_part1.head())

# Opcional: inspeccionar información general del archivo
print(ids_part1.info())

           song_name artist_name  year   views  \
0          Killa Cam     Cam'ron  2004  173166
1  Forgive Me Father    Fabolous  2003    4743
2       Down and Out     Cam'ron  2004  144404
3             Fly In   Lil Wayne  2005   78271
4     Lollipop Remix   Lil Wayne  2008  580832

                                              lyrics language
0  [Chorus: Opera Steve & Cam'ron]\nKilla Cam, Ki...       en
1  Maybe cause I'm eatin\nAnd these bastards fien...       en
2  [Produced by Kanye West and Brian Miller]\n\n[...       en
3  [Intro]\nSo they ask me\n"Young boy\nWhat you ...       en
4  [Intro: Lil Wayne]\nHaha\nUh-huh\nNo homo (You...       en
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   song_name    99999 non-null   object
 1   artist_name  100000 non-null  object
 2   year         100000 non-null  int64
 3   views        100000 non-null  int64
 4   lyrics       100000 non-null  object
 5   language     99458 non-null   object
dtypes: int64(2), object(4)
memory usage: 4.6+ MB
None

In [18]:
pd.set_option('display.max_columns', None)  # Muestra todas las columnas

In [29]:
ids_part1['lyrics'] = ids_part1['lyrics'].str.replace('\n', ' ')
ids_part1.sample(50)

,song_name,artist_name,year,views,lyrics,language
54234,Toque-Toque,Da Weasel,2007,1713,[Verso 1: Pacman] Eu preciso de sentir aquele ...,pt
37292,I Got You,Del The Funky Homosapien,2008,269,In my own words said you slightly drunken vert...,en
51763,Nate57,Nate57,2010,4119,"[Part 1] Ja, ich lauf durch die Street, mache ...",de
27974,Great to Be There Outro,Wiz Khalifa,2009,2872,(Intro) Yeah man It's your boy Young Khalifa m...,en
19444,Zoo Two,Ol' Dirty Bastard,2002,1015,"[Intro] I just want all y'all to know, the rea...",en
76978,9 To 5,There For Tomorrow,2009,571,[Verse 1] Out of touch with yourself as the li...,en
38279,The Wager,Silent Knight,2008,95,[Verse One] [8thW1]: Peace of mind's the only ...,en
94401,You Win Again,Keith Richards,2001,126,The news is out all over town That you've been...,en
57732,Hurricane,2AM Club,2010,222,[Verse 1: Tyler] They say something like it's ...,en
22892,All I Have,S.L.A.B.,2004,727,"(*talking*) What's up baby, Paul Wall I'm Slow...",en
88262,PorobiCię Hidden track,Grubson,2009,260,[Refren] Gdy będziesz słuchał tego kawałka - o...,pl
28798,Teufelskreis,Bushido,2004,2390,"[Intro: Sentino] Badam-bam-bam Ah, yo [Part 1...",de
48487,Unconditional,The Bravery,2005,2331,(Verse) I spent my whole life surrounded And I...,en
58512,Photoshop Handsome,Everything Everything,2010,8666,[Verse 1] I will gain an extra life When I get...,en
23176,LAX,Snoop Dogg,2006,4616,"[Hook] ""Oh... Cali? ""No doubt"" ""LAX"" ""Oh... Ca...",en
14248,Greyhound Part 2 GZA Mix,The Jon Spencer Blues Explosion,2001,492,"* originally appeared on ""Experimental Remixes...",en
45633,Round Round,Selena Gomez & The Scene,2010,26286,[Intro] Round and round Round and round Round ...,en
7019,Tired,Bronze Nazareth,2005,80,"[Bronze Nazareth] My name is Bronze, nigga, I'...",en
18800,Once a Week,Mystic,2001,451,"[Verse 1] I ain't wanna be your woman, ain't w...",en
95466,In My Dreams,T3rr0r 3rr0r,2010,82,Did I tell you about that little boy with the ...,en
21490,More Like You,Rehab,2000,1612,An excess rules everything I do So tell me how...,en
219,The Dynasty Intro,JAY-Z,2000,141796,[Produced by Just Blaze] [Intro] It's the Dyn...,en
26757,A1,Bobby Brackins,2010,1339,I'm gettin' stupid cake Get in the stupid club...,en
29556,Vida Loka Pt. 1,Racionais MC's,2002,49760,[Intro] Mano Brown: Vagabunda... Queria atacar...,pt
4626,Cry Baby,Afu-Ra,2005,4491,"[Chorus: Lady Blue (Q)] I'm sorry, look what t...",en
30326,Freeze Me,Young Dro,2010,9602,[Verse 1: Young Dro] Dro; that's all nigga Car...,en
93197,O Som Da Chapada,Estakazero,2005,19,Numa noite de bobera Longe da poluição Fui des...,pt
67007,Dawno Temu,Buka,2010,150,"[Hook] I nie pytaj czemu To był dawno, dawno t...",pl
96825,I Wanna Be That Man,Aaron Lines,2005,98,"Baby, when you smile at me I know that you're ...",en
1201,Point to Prove,Diggy,2009,853,[Intro] You know they said I was born with a g...,en
76255,Gold Splatter,Black Moth Super Rainbow,2009,2169,"Beautiful friend, you're my only friend Beauti...",en
50370,I Have Loved You,Jessica Simpson,2003,622,[Verse 1] Remember that blue crystal sky The s...,en
80554,Phone Went West,My Morning Jacket,2001,3791,Is there a doctor in the house tonight? If the...,en
80399,Ruhrpott 4 Life,Favorite,2005,581,"[Part 1] Ich bin ein Psycho wie Mantis, ich fi...",de
76601,Anybody There,The Script,2008,2269,[Refrain] My head is saying no But my heart ke...,en
63809,Standing,Joss Whedon,2001,2372,[Giles] You're not ready for the world outside...,en
32289,From Out of Nowhere,Five Finger Death Punch,2010,1363,"[Verse 1] Tossed into my mind, stirring the ca...",en
25815,Saturday Night Live,Xzibit,2004,1231,[Intro] Ahhh! We bout to go this motherfuckin ...,en
39219,J’aime trop ton boule Shake ton booty,Fatal Bazooka,2007,12273,"Ouais, ce soir j'arrive dans le club en mode c...",fr
59621,Discographie rap - 2001,Genius France,2001,7977,Janvier : * 15/01 : OGB - Vitry Club - 30/01 :...,fr
67685,Scenario 2008,Re-Up Gang,2008,548,[Hook] You see the raw is back the score is ba...,en
95806,Never Gonna Give You Up,Able-X,2007,268,We're no strangers to love You know the rules ...,en
2462,Justins Beaver,Rucka Rucka Ali,2010,5260,[Chorus] I know some faggot JB And everytime h...,en
43527,Nemesis,Bushido,2006,12215,[Hook: Bushido] (2x) Hör mal was ich dir sage:...,de
34111,Lost,Rhyme Asylum,2008,5149,[Verse 1: Skirmish] I was birthed in a savage ...,en
6348,Blazing Arrow,Blackalicious,2002,11772,[Verse 1: Gift of Gab] Amazing phase your days...,en
27348,Amok,Olli Banjo,2003,502,[Olli Banjo] Kennst du die tage an denen du in...,de
84612,Jakby Nie Było,Szajka,2010,223,[Zwrotka 1: Pyku] Po każdej nocy musi przyjść ...,pl
74078,In the Arms of Buffalo Bill,The Felice Brothers,2006,107,[Verse 1] Tonight’s the nicest night this year...,en
62571,Insomnia,Craig David,2008,23157,"[Intro] Jim Beanz, give it to me, oh baby I ca...",en

In [5]:
import pandas as pd
 #Cargar el archiv"o CSV
file_path = r"C:\Users\solan\Downloads\get_data_from_songs\data\final2.csv"
df = pd.read_csv(file_path)

In [5]:
import torch

# Verificar si CUDA está disponible
print("¿GPU disponible?", torch.cuda.is_available())

# Verificar qué dispositivo está disponible
if torch.cuda.is_available():
    print("Nombre de GPU:", torch.cuda.get_device_name(0))

AttributeError: partially initialized module 'torch' has no attribute 'version' (most likely due to a circular import)

In [43]:

# MODIFICAR PARA SACAR DATOS DE SPOTYFY Y LAST FM
data = r'C:\Users\solan\Downloads\get_data_from_songs\data\raw\limpios_bea.csv'
df = pd.read_csv(data)
# Mostrar ejemplos de las columnas 'artist_name', 'song_name' y 'spotify_url'
df.sample(10)

,artist_name,song_name,recording_id,danceable,not_danceable,male,female,timbre_bright,timbre_dark,tonal,...,album_name,album_release_date,duration_ms,popularity,genres,tags,year,views,lyrics,language
10017,solillaquists of sound,new sheriff in town,d2d1ffe7-53c5-4593-a5d4-918b9a14740b,0.995,0.005,0.260,0.740,0.367,0.633,0.602,...,No More Heroes,2009-08-04,248304.0,12.0,"Hip-Hop, hip hop, rap, underground rap, underground hip hop","Hip-Hop, comics, sxsw 2010",2009,1667,"[Verse 1: Swamburger] Scenery: block’s been mobbed and robbed of Lack-lust shown, doubt runs around pub Routine day, repeat and mock plot Barflies flock then stopped the sock-hop Dance to the rhythm of a similar drum Some never will admit a better feeling we sung Numb to the point of popcorn rock is hip Burn CD’s! Download, cop and quit Loose lips let loose on ego trips Skill decreased heavy when emo hit No plan for the future leadership Follow hollow dreams. Model this steelo kit Stop-go pace, no destination... Go Speed-race chase that mental patient. Stop Who erased living life copas(t)etic... Edit credit from the ones who’s supposed to get it? We opposed but let it Happen anyway. A penny weighs a tongue Plus an act with a knack for beef... But to the enemy, never the friend of me Handing understanding I can manage Manning time like “we demand this.” Recess dropped, now they want business Kids turn tricks like Kris on Christmas Crime and little fishes (gunshot) “Yo what is this?” Standstill neutrals push the boat MC’s ain’t teaching but push the dope Somehow Coke got us on TV spokes Filling up the GAPs, stealing up the raps Now the world think we on crack Good looking out I’ll remember what it’s all about cause I am... [Hook: Swamburger] ...the new Billie Holiday Cab Calloway, new Nina Simone New Sly and the Family Stone New 88 tapes, new experience and new fate New scenery and update World-renowned Solillaquists of Sound... New sheriff in town [Verse 2: Alexandrah] Why weak minded try to find a choir and wanna preach like teacher Script down sit down facts and made up Seizure as a leisure all your sheep could take up In the lobby of physician’s forced a needle in the fetal Fed a blend of distress Dis-trust then goes frontline followed By divide at relation woes Early bird here gets hurt first Fake bait shock at no worm Hate this tasteless situation? Replace nature fake of innovation? Great shouldn’t be remaining in waiting in aim of taking blame No seraph’s fault with assaulted involvement in every stake claimed Case of break, rape of address Vacate cranium, man do the rest Found best kept property of government suddenly Now youth owes rent, tenant of stress Not much more than horribly presented Sent a notice for removal of the truth Said was anticipated a basic assimilation Mental ground’s been plowed It ain’t ever gonna be done Back on words like worth of current currency Cools slack the noose and refute proof of urgency Rid it now, get it out Know urges, where they come from Understand why hurry Purge the lurking wicked fitted Dimwits missed by missions of a liquid frigid Stellar wiz kids pay insipid interest When it mimics pictures flipped in gist and indicates A quick dismiss of drastic on conspire list The term is prison sift [Bridge: DiViNCi] Everybody Move! Everybody Move! Cause if you don’t, you’ll never see the revolution ever come to be Everybody Move! Everybody Move! Cause if you don’t, you’ll never see the revolution ever come to be La La La La La La LAA LAA LAAA... [Hook]",en
8669,justin bieber,never let you go,81e2b63c-7fd7-49ed-a2e0-cd00e209c1b7,1.000,0.000,0.974,0.026,1.000,0.000,0.111,...,My World 2.0,2010-01-01,264400.0,59.0,"pop, black metal, justin bieber, rnb, Hip-Hop","justin bieber, pop, love songs, Canadian, upbeat",2010,45081,"[Verse 1] They say that hate has been sent So let loose the talk of love Before they outlaw the kiss Baby, give me one last hug There's a dream that I've been chasing Want so badly for it to be reality And when you hold my hand Then I understand that it's meant to be Cause baby, when you're with me [Chorus] It's like an angel came by and took me to heaven Like you took me to heaven, girl Cause when I stare in your eyes, it couldn't be better I don't want you to go, oh no, so Let the music blast, we gon' do our dance Bring the doubters on, they don't matter at all Cause this life's too long and this love's too strong So baby, know for sure that I'll never let you go [Verse 2] I got my favorite girl Not feeling no pain, no fear Don't have a care in the world Why would I when you are here? There's a moment I've been chasing And I finally caught it out on this floor Baby, there's no hesitation No reservation by taking a chance and more Oh no, because [Chorus] It's like an angel came by and took me to heaven Like you took me to heaven, girl Cause when I stare in your eyes, it couldn't be better I don't want you to go, oh no, so Let the music blast, we gon' do our dance Bring the doubters on, they don't matter at all Cause this life's too long and this love's too strong So baby, know for sure that I'll never let you go [Breakdown] It's like an angel came by and took me to heaven Like you took me to heaven, girl Cause when I stare in your eyes, it couldn't be better I don't want you to go, oh no, so [Bridge] Take my hand, let's just dance Watch my feet, follow me Don't be scared, girl, I'm here If you didn't know, this is love [Chorus - Shortened] Let the music blast, we gon' do our dance Bring the doubters on, they don't matter at all Cause this life's too long and this love's too strong So baby, know for sure that I'll never let you go [Outro] So don't fear, don't you worry 'bout a thing I am here, right here (I'll never let you go) Don't shed a tear Whenever you need me, I'll be here (I'll never let you go) Oh no, oh no, oh I'll never let you go Oh no, oh no, oh I'll never let you go",en
5599,jadakiss,bring you down,c17bc067-97fb-49a5-8575-d2b277663ee4,1.000,0.000,0.718,0.282,0.487,0.513,0.081,...,Kiss Of Death,2004-01-01,219106.0,28.0,"rap, Hip-Hop, east coast rap, hip hop, new york","Hip-Hop, East Coast, jadakiss",2004,9151,"[Verse 1] Top of the food chain, It's just the way that I do things The dungaree seats in the blue Range I'm working with new change, a Gemini nigga with mood swings Had the fiends looking for new things I stopped playin' with birds and started playin' with words The money wasn't right, so I had to stay on the curb And I'll be a player later. But for now Call me pootay 'Kiss, if not that? Montega Jada I kick hard bars and blow hard weed And be everywhere, cause I move at God's speed And my aim is to make y'all bleed Y'all got embarrassed in the class when the teacher used to make y'all read Uh-huh, Mind over matter And that's all good but fuck that My new shit is spine over bladder And everybody tryin'a get to the top, and that's all good too But right now - I'm on the ladder [Hook] Look at you then, and (uh-huh) Look at you now. (yeah) Don't let this cold cold world,(uh-uhhh) Bring you down [Verse 2] I know your queen got her eyes on me I got my eyes on your queen, The SMG is Heineken green Mad thing is you know before long that we gon' get it on My kit costs thirty and ten to put it on No tints, windows clean - heavy Windex Gears on the steering wheel, I shift 'em with my index Real life - it's just in another form Kiss of Death, it's about to be another storm I'm a goddamn raging bull Stay out of jail by just tellin' myself the cage is full Got niggas on the payroll, just to squeeze You're in no position to challenge my expertise They get a bonus if they leave you Old school - from the era of the 45's with the penny on the needle Boss of the bosses, so please don't violate or cross him Or you'll be the corpse of the corpses [Hook] [Verse 3] Uh- Huh, You know the word anger Is just one letter short of the word danger, and I ain't no stranger Never use a gat more than twice if you don't clean it And never say fuck something if you don't mean it And when it comes to life, the route you've been using thus far ain't working right? Take the scenic Whatever faith you got, put in a crook Wanna hide something from a nigga? Put it in a book Trust me, this album, the vapour's gon' go around If you ain't hot, you need paper to throw around Yeah, it's getting clearer every day When you wake up in the morning, look in the mirror and say [Hook]",en
13307,red hot chili peppers,mercy mercy,493faf56-8a49-4777-aff1-ab67b0fd78d5,0.544,0.456,0.000,1.000,0.780,0.220,0.659,...,Tell Me Baby,2006-07-17,239920.0,26.0,"rock, alternative rock, alternative, Funk Rock, funk","b-side, alternative rock, alternative, genius, Red Hot Chili Peppers",2006,1693,"[Verse 1] Oh mercy, mercy, mercy me I look around, I need another remedy The I don't know is philosophy Better yet, I'll let you get ahead of me [Verse 2] Oh mercy, mercy, mercy me Come around, I need another enemy Anyone could clearly see A summer breeze is part of my anatomy [Pre-Chorus 1] When it's written in Britain, we get a little smitten Like a kitten, a cuddle is where I'm benefiting Any higher the fire would have to petrify her Upon the wire the flyer is gonna satisfy her [Chorus] My love is forever My love it can feel this My breathless defender Step forward and steal this [Verse 2] Mercy, mercy, mercy me Coming down, I gotta case of gravity Even though we disagree Give a kiss 'cause life could be the death of me [Pre-Chorus 2] Acrobatic, the static is getting too dramatic Comin' down with the system, we'll get it systematic Facilitating the mating, my love is circulating Rejuvenating the fading but never dialating [Chorus] My love is forever My love it can feel this My breathless defender Step forward and steal this [Verse 3] Mercy, mercy, mercy me Lovin' on the color of an Emily Easy as a guarantee Better yet, I'll show you what you wanna see [Chorus] My love is forever My love, you to feel this My breathless defender Step forward and steal this [Outro] We aim to forever I want you to feel this My gentle defender Step forward and steal this",en
13142,lim,tous dans la merde,f5c96878-e395-4d82-a106-246354cc2311,0.986,0.014,0.204,0.796,0.907,0.093,0.847,...,Enfant du ghetto,2013-10-23,264620.0,19.0,"plagiarism, stupid, rap francais, Officially Shit, Rap FR",caca,2005,2307,"[Couplet : LIM] À 25 ans grand, je galère encore khoya Ça craint non ? C'est pire vu qu'j'suis pas l'seul dans ce cas Exemple : c'était un soir comme d'hab, défoncé j'devais avoir 13 piges Pas l'envie d'pioncer donc j'traîne, tise Sur l'avenue kho vu qu'il y a de la meuf T'as vu j'suis saoul, seul et sans sous et j'veux une belle paire de sse-fe Mais y'a rien, que dalle, que du vent et des keufs, des vandales L'embrouille, le scandale alors je décide de rentrer au tier-quar Ouais, ouais D'aller sur le terrain et de péter 2-3 yen-clar Mais sur le chemin je tombe sur mon pote Kaiser Le sosie de Sosé posé à son poste danger Car il me dit : ""Lim ce soir j'veux niquer la France"" Coïncidence, moi aussi j'ai ma crise d'adolescence Alors on ne pense plus aux circonstances J'veux faire danser les shmitts Dans cette ue-r où ils ont fait couler notre ang-s J'sais que c'est triste mais bon j'ai l'intention d'foutre la merde Donc j'enchaîne shit, herbe, tise jusqu'à c'que je gerbe Tout comme ce barbu dans ce bar beurre, mal barré Barbare, barbeur, taré, agresseur Et yo écoute kho, j'pointe à cette fête foraine Là où je rejoins Espion, Deble et un peloton de chiennes Mais il y a trop de haine qui règne donc ça crée des histoires Avec un quartier voisin qui en vain essaie de nous avoir Et là une droite décolle donc la merde commence Sous alcool, gogole, j'ai plus rien à perdre donc j'relance Un coup de boule, pas de bol, j'casse le pif de ce bimboule Qui comme une folle crie ""je vais t'égorger comme une poule"" ""Regarde, ils se sauvent comme des pédales Laisse Espion, ils savent bien que la vie est brutale"" Mais Deble lui sort son schlass, fuse Pour en planter un, histoire d'lui faire un deuxième anus Mais la poisse au même moment une voiture d'inspecteurs passe Grillé, les porcs sortent, attrapent mon pote et s'cassent Tellement vite qu'on a rien pu faire, nique sa mère On va venger notre frère même s'il faut qu'on aille en Enfer Alors fais tourner l'joint d'la taille de mon majeur Que j'dédie, au maire et à son adjoint directeur De la jeunesse et sport, des promesses mais quel sport ? Quand on s'en met plein les poches on appelle ça confort Comme quand j'ai posé mon cul sur ce manège Mais l'embrouille me lâche plus vu qu'un putain de cortège De forains balaises échangent des coups de poing avec mes soces fonce-dés au Bayley's J'rentre dans la baston et là ça s'gate comme dans Stargate Mate cette matraque télescopique mec, fusil à pompe handek Et ça frappe sec et tout ça pour 5 keu-sse C'est peut-être keu-sse pour finir dans une fosse Et là les keufs arrivent en masse alors faut s'tailler Vite rentrer au quartier pour être en sécurité Et lors d'la cavale, j'avais une paire de pompes trop ge-lar Je l'ai jeté et comme un con j'ai perdu mes papelards Alors je reviens sur les lieux pour les retrouver Ouais faut pas qu'les forains puissent venir me soulever Chez moi, n'importe quand, putain j'les r'trouve pas Faut que je me barre, ouais parce que c'est le halla Alors j'rentre, à travers le bois sombre Hassoul demain mec, ouais, j'reviendrai en nombre Mais sur le trajet j'entends une go-va qui débarque J'me dis qu'c'est les keufs alors scret-di je me décharge Mais c'était un 4x4, avec une dizaine de gars pliés en 4 Avec leurs battes qui m'insultent de sale rab-za Et qui disent, vouloir me caner C'est la merde, ouais, j'ai dû me sauver [Outro : Cens Nino] Une journée d'galère Comme une autre Personne n'est a l'abri d'une balle, d'un coup d'schlass ou autre Mais c'est la vie à base d'embrouille, de douilles, de couilles Mais handek, si tu passes à la fouille Faut resserrer les ranges Ramener les euros, faire des heureux Quand c'est la merde ou quand t'as l'ventre creux Premier dans la danse Je chante pour ma délinquance, Impertinent, ouvrez vos oreilles Je viens réveiller la France",fr
4181,the coup,lazymuthafucka,e9ee09eb-8ef7-43d1-aff3-1a9bd464cae8,0.978,0.022,0.047,0.953,0.676,0.324,0.435,...,Party Music,2001-11-06,284493.0,9.0,"Hip-Hop, rap, political, hip hop, political rap","Hip-Hop, personal favourites, political hip-hop, west coast hip-hop",2001,1775,"[Boots] Now when I go to bed it's almost time to wake up Tryin' not to go to jail, tryin' not to cake up And even when I serve soda it would be cold as fuck Chillin' in my sock, servin' ice for ten bucks And you'd be in the house, all warm and shit And ya ass got the sweater with the fire lit And whatever ya want you ain't gotta lift a finger If ya wanna a glass of water hit the maid on the ringer Got a job for you under this hot ass sun Tellin' me to hurry up and get some more shit done I be so tired when I spit all my word slur together Got so many calluses my hands are like leather Watchin' MTV in yo big ass chair Tryin' out slang words while you combin' ya hair Ya productivity is wack bring that box here fo-sheezy Go get some coffee punch out before ya leave Got cho' feet up on the desk noddin' off to sleep While I lift, push, pull, dig, sweat, and sweep I could work hard all my life and in the end still suffer Cause the world is controlled by you lazy motherfuckers [Hook] Lazy motherfucker, lazy mother-fucker You's a lazy motherfucker, lazy mother-fucker [Boots] Now you don't wash ya ass, you got a personal bather If you roll out of bed it's like you doin' a favor You was born into paper and that behavior For a midnight snack, you have the bedroom catered You ain't never learned to drive or tie ya shoe I got my ear to the street and my eye on you You got a secretary to write down your thoughts On how to make us work hard and fatten up your vaults TV say if ya poor, you must be slow and shiftless But you pay em' to say that so we don't want it different Got a cook and a girl to bring the tray for you You're hearin' this cause somebody pushed play for you My head is poundin' now and my hands are shakin' To keep my eyelids open takes concentration I don't get no rest it's just a stay alive hustle Making you stay rich without you moving a muscle You think of people as your tool So when your dick salute You have a butler get the phone and call a prostitute And say your sex drive's stronger than the engine of a trucker But she'll have to be on top cause you a lazy motherfucker [Hook] [Boots] A hundred person house there just to sanitize You know you don't give a fuck but they all despise you Millions over millions makin' shit for you to sell But police on alert just in case we rebel But it's gon' happen captain, hope ya know that's why I'm rappin' Once the toes start tappin, hands with gats start clappin Cause this whole system's waitin' for you to kick it in Paris Or roll through Hong Kong in a rickshaw carriage So when you spend a dollar that's ten seconds of my time And when ya spend a billion that's my life and that's a crime Cause to me life is hard like a track that I'm reppin' on Callin' for the freedom of the backs that you steppin' on Later for the pull up ya boot strap factor Hard work got me to the chiropractor But we can work hard to take back the bread and butter Cause all these multi-millionaires is lazy motherfuckers [Hook repeated to end]",en

In [48]:
import pandas as pd

# Aumenta el ancho máximo de las columnas
pd.set_option('display.max_rows', None)  # Muestra todas las filas
pd.set_option('display.max_columns', None)  # Muestra todas las columnas
pd.set_option('display.width', 1000)  # Ajusta el ancho máximo de la salida

df.isnull().sum()

artist_name                              0
song_name                                0
recording_id                             0
danceable                                0
not_danceable                            0
male                                     0
female                                   0
timbre_bright                            0
timbre_dark                              0
tonal                                    0
atonal                                   0
instrumental                             0
voice                                    0
dortmund_alternative                     0
dortmund_blues                           0
dortmund_electronic                      0
dortmund_folkcountry                     0
dortmund_funksoulrnb                     0
dortmund_jazz                            0
dortmund_pop                             0
dortmund_raphiphop                       0
dortmund_rock                            0
electronic_ambient                       0
electronic_dnb                           0
electronic_house                         0
electronic_techno                        0
electronic_trance                        0
rosamerica_cla                           0
rosamerica_dan                           0
rosamerica_hip                           0
rosamerica_jaz                           0
rosamerica_pop                           0
rosamerica_rhy                           0
rosamerica_roc                           0
rosamerica_spe                           0
tzanetakis_blu                           0
tzanetakis_cla                           0
tzanetakis_cou                           0
tzanetakis_dis                           0
tzanetakis_hip                           0
tzanetakis_jaz                           0
tzanetakis_met                           0
tzanetakis_pop                           0
tzanetakis_reg                           0
tzanetakis_roc                           0
ismir04_rhythm_ChaChaCha                 0
ismir04_rhythm_Jive                      0
ismir04_rhythm_Quickstep                 0
ismir04_rhythm_Rumba-American            0
ismir04_rhythm_Rumba-International       0
ismir04_rhythm_Rumba-Misc                0
ismir04_rhythm_Samba                     0
ismir04_rhythm_Tango                     0
ismir04_rhythm_VienneseWaltz             0
ismir04_rhythm_Waltz                     0
mood_acoustic                            0
mood_not_acoustic                        0
mood_aggressive                          0
mood_not_aggressive                      0
mood_electronic                          0
mood_not_electronic                      0
mood_happy                               0
mood_not_happy                           0
mood_party                               0
mood_not_party                           0
mood_relaxed                             0
mood_not_relaxed                         0
mood_sad                                 0
mood_not_sad                             0
mood_mirex1                              0
mood_mirex2                              0
mood_mirex3                              0
mood_mirex4                              0
mood_mirex5                              0
artistsort                            5052
genre                                 3731
releasecountry                        9790
albumartistsort                       4713
label                                 5665
tracknumber                            348
spotify_url                              0
album_name                               0
album_release_date                       0
duration_ms                              0
popularity                               0
genres                                   0
tags                                     0
year                                     0
views                                    0
lyrics                                   0
language                                35
dtype: int64

In [1]:
df = df.dropna(subset=['spotify_url'])

NameError: name 'df' is not defined

In [49]:
columns_to_drop = ['artistsort','releasecountry','albumartistsort','label','tracknumber']
df = df.drop(columns=columns_to_drop)

In [50]:
ruta = r'C:\Users\solan\Downloads\get_data_from_songs\data\raw\bea1.csv'
df.to_csv(ruta, index=False)

 "None of [Index(['ARTIST_NAME', 'SONG_NAME'], dtype='object')] are in the [columns]"  

 request spotify y request last fm ¿son necesarias?

 *Ambos scrips buscan a través de 'ARTIST_NAME', 'SONG_NAME' - lo que sería song_name y artist_name las de genius

- SPOTIFY DEVUELVE

         'SPOTIFY_URL': None,
        'ALBUM_NAME': None,
        'ALBUM_RELEASE_DATE': None,
        'DURATION_MS': None,
        'POPULARITY': None,
- LAST FM DEVUELVE:

    row['genres'] = genres
    row['tags'] = tags

In [13]:
# Guardar el DataFrame modificado en un nuevo archivo CSV
#output_path = r"C:\Users\solan\Downloads\get_data_from_songs\data\processed\completed_cleaned.csv"
#completed.to_csv(output_path, index=False)

#print(f"Archivo guardado exitosamente en: {output_path}")

Archivo guardado exitosamente en: C:\Users\solan\Downloads\get_data_from_songs\data\processed\completed_cleaned.csv